### ISSUE TITLE
Laggy PS button menu in PS1 games

### ISSUE THREAD

**Issue by ajbritain4** [TheOfficialFloW/Adrenaline#100]
PS button menu to quit back to XMB is laggy and unreliable on Vita 1000 and PS TV running 5.1, updated over network from 4.2. Sometimes just freezes the game until the button is pressed again, sometimes comes up but doesn't respond to button presses, sometimes it works fine. Only seems to happen in PS1 games and not PSP games as far as I can tell.

**Comment by TheOfficialFloW** [comment]
This issue is hard to fix.

**Comment by ajbritain4** [comment]
No worries! Just thought I'd bring it up as it didn't happen in previous versions

**Comment by FlexingTiger** [comment]
Look at my new pull request, the problem you have encountered, like freezing... should be fixed.

**Comment by FlexingTiger** [comment]
Exit menu can't be shown, whick looks like game freezing.
