### ISSUE TITLE
Slight conflict between the Vita's screenshot function and Adrenaline's controls

### ISSUE THREAD

**Issue by LegendOfAB** [TheOfficialFloW/Adrenaline#105]
In adrenaline, pressing the PS button instantly brings up the PSP quit menu. So, taking a screenshot in a PSP game basically means pressing the PS button once to bring up the menu, then pressing it again (to hide it) along with the start button to trigger the screenshot function. 

(Small as it may seem, it would honestly mean a great deal if this was adjusted slightly)

**Comment by StepS-** [comment]
Possible solution: open the quit menu on keyup and not on keydown.

**Comment by LegendOfAB** [comment]
It's funny how i am currently reading a book about Python (first programming language) and the only reason i immediately understood what "keydown" and "keyup" means is because of the chapter i've started working through just today. _That's pretty dang cool._

Anywho, that sounds pretty good to me. @
