### ISSUE TITLE
Odd Analog Issue In Adrenaline

### ISSUE THREAD

**Issue by deathscreton** [TheOfficialFloW/Adrenaline#107]
I've been experiencing this odd issue where holding up (in this general direction; happens Up-Left and Up-Right) on the Analog Stick in any PSP or PSX game causes the person you're controlling to stutter step forwards, like the analog stick is dirty or failing, however, this issue isn't present in PSV games and I've used a hardware tester to make sure the analog stick was working properly and I haven't seen any issues regarding it. 

Any idea what may be going on? 

EDIT: My right analog stick is now doing this in all directions. I haven't had any issues with them until I started playing PSP games and PSX games on the vita. HALP.

EDIT2: I used a key tester for the PSP in Adrenaline. The problem happens a bit there too, not nearly as often as in game however. I then tested using another key tester, separate program, and the problem didn't show itself. WTF is going on?

**Comment by TheOfficialFloW** [comment]
Check your touch remappings...
