### ISSUE TITLE
The screen size and screen mode (PS1) options do not work on PSTV

### ISSUE THREAD

**Issue by mathieulh** [TheOfficialFloW/Adrenaline#112]
As the title says, The screen size and screen mode (PS1) options do not work on PSTV using adrenaline 5.1, this is even with custom graphics filtering selected. Changing these settings have no effects whatsoever.

I am currently running on HDMI 720p output using fill RGB range (not sure if that changes anything to the issue)

**Comment by TheOfficialFloW** [comment]
I have introduced a bug in 5.1, but it has been fixed with this commit: https://github.com/TheOfficialFloW/Adrenaline/commit/1753d7da9a3abd8e694761cba0fb88fb46e57442
For now, just disable smooth graphics.

**Comment by mathieulh** [comment]
Thanks, disabling smooth graphics fixes the issue
