### ISSUE TITLE
PSTV & PS1 Bilinear Filtering

### ISSUE THREAD

**Issue by Burnt-Lasagna** [TheOfficialFloW/Adrenaline#115]
Hi,
As some know, the PSTV doesn't have official settings for disabling Bilinear Filtering (it's forced on). Luckily, recent versions of Adrenaline enable the user to disable bilinear filtering on PSP games by setting Smooth Graphics to "Off" in the Adrenaline Menu. This is wonderful, however, these settings don't seem to take effect when playing PS1 games.

No matter what I set, PS1 games always have bilinear filtering on, regardless of the "Smooth Graphics" setting. Also, the PSTV doesn't provide official settings for disabling it on PS1. 

If this option can be made to work with PS1 that would be great.

**Comment by rsn8887** [comment]
For me it is different, on VitaTV, when I set graphics to "original," bilinear filtering is always off for PS1 games, regardless of any settings.

**Comment by IcySon55** [comment]
Settings graphics to Original is the same as turning off Adrenaline's filtering engine and instead using the default one from the emulator.

**Comment by rsn8887** [comment]
Using Adrenaline 6-fix with PS1 titles on PSTV, graphics seem to change between "smooth" and "not smooth" on their own. I have both graphics set to "original," and smooth graphics set to "off."

- When I first start Adrenaline, the graphics are not smooth
- When I press the PS button while playing a PS1 title for a short duration to bring up the gray "do you want to exit" dialog, I can tell on this screen that it has smoothed graphics
- From then on, graphics in both PS1 and PSP screens are both smooth until I restart Adrenaline.

I think the correct behavior would be for the Smooth Graphics setting to do nothing whenever "original" graphics are selected, just to follow whatever an original PSTV would do?

**Comment by IcySon55** [comment]
It seems that bringing up the PSP quit menu switches the graphics mode to PSP (which has the default smoothing if you select Original for PSP) and then if you return to the PS1 game the filter persists instead of going back to no smoothing.
