### ISSUE TITLE
Does not work with Sd card mounted.

### ISSUE THREAD

**Issue by a7mag3ddon** [TheOfficialFloW/Adrenaline#117]
Does not load with Hankaku Enso and SD mounted at boot as UX0:/

**Comment by chaoskagami** [comment]
Check your config.txt. The order matters.

If adrenaline is on the gamecard, you have to load it AFTER the gamesd plugin, not before; otherwise it attempts to read off the memory card.

**Comment by a7mag3ddon** [comment]
So I need to to add the adrenaline add-on into UR0:/ config.txt?

Currently the gamesd plugin loads first from that location then I think UX0:/Tai/config.txt loads next ?

**Comment by a7mag3ddon** [comment]
I think it is after because adrenaline is installed on SD only, and it loads with MiNiS then juat sits at a black screen, then errors with C1-2858-3

**Comment by chaoskagami** [comment]
Your config.txt should be on ur0: if you're using any ux0: remounting plugin - delete ux0:tai/config.txt.

Make sure it looks like this:
```
*KERNEL
ur0:tai/gamesd.skprx
ux0:tai/adrenaline.skprx
``

The line order is the important part. If adrenaline.skprx is first, it will attempt to load off the vita memory card and subsequently fail, since ux0: is not yet redirected.

**Comment by a7mag3ddon** [comment]
Ok, i think i understand.

**Comment by a7mag3ddon** [comment]
Thank you it works! I have no idea where that UX0:/config.txt file came from as i deleted it as part of the SD2Vita install process.
