### ISSUE TITLE
PSP Exit Game Menu Becomes Invisible

### ISSUE THREAD

**Issue by slickrasta** [TheOfficialFloW/Adrenaline#120]
Most of the time when I try to open the menu in a PSX game in Adrenaline (press home once) the Exit Game yes or no comes up but it is not visible 95%+ of the time. Also cwcheat sometimes doesn't open just freezes the game then you have to cancel and try again to open the menu, sometimes taking a few times. I believe the latter issue has always been a bug with cwcheat even on original PSP so I doubt you can fix that but the Exit Game menu glitch would be nice to fix if possible.

**Comment by xSASxZaros** [comment]
I am having the same issue when it comes to the exit menu while playing PSX games - My CWCheats works fine though - Although I don't use it very often so maybe I've just been lucky.

**Comment by KawaiiAurora** [comment]
I had the same issue with Adrenaline-5.1 BUT the issue got fixed when I used this mod that adds uma0 support which is based on the latest Adrenaline source code.

[http://www.psx-place.com/threads/adrenaline-last-source-and-uma0-support.14468/](http://www.psx-place.com/threads/adrenaline-last-source-and-uma0-support.14468/)

**Comment by slickrasta** [comment]
Thanks very much indeed that version compiled from the newest source code fixes the issue! =)
