### ISSUE TITLE
uma0: or ur0: Without GAME folder no ISO's or CSO's are showing

### ISSUE THREAD

**Issue by xadox-1st** [TheOfficialFloW/Adrenaline#121]
While using **uma0:** or **ur0:** as emulated memory card storage no _ISO's_ or _CSO's_ are shown if there is no _GAME_ folder under _pspemu/psp/_.

**Comment by TheOfficialFloW** [comment]
Fixed in https://github.com/TheOfficialFloW/Adrenaline/commit/f61187a4cdb71f52edff6454ccb6a6f45cf77fc9
