### ISSUE TITLE
PSX PSN Save State Audio Issue

### ISSUE THREAD

**Issue by slickrasta** [TheOfficialFloW/Adrenaline#125]
I've been playing Final Fantasy 7-9, Legend of Dragoon and Xenogears all official PSN downloads using them on Adrenaline with cwcheat. Everything works quite well but when I do save state about 30% of the time it messes up the audio for instance the music will stop but just certain sound effects will play or others it will glitch, this is fixed by Quit Game then restarting the title, reloading the save state just brings the audio glitch back. Also the snapshot of the save states is just black, that only started on the 5 update before it actually had proper screenshots for each save state.

**Comment by TheOfficialFloW** [comment]
Hard to solve that.
