### ISSUE TITLE
Adding support for the 6.61 PSP-N1000 (psp go) firmware

### ISSUE THREAD

**Issue by mathieulh** [TheOfficialFloW/Adrenaline#127]
This is an enhancement suggestion. Since the PS Vita doesn't sport a physical UMD Drive (or spock) there is no advantage in using the psp-1000 firmware over the psp go firmware, especially with the lack of Media Engine making UMD Video streams incompatible.

The PSP-N1000 kernel and vsh would allow us to use ef0:/ and ms0:/ (which we could map/mount to different devices such as uma0:/ and ux0:/) and thus use different devices at the same time seemlessly.
impose.prx also supports a save state feature ("pause") out of the box.

**Comment by TheOfficialFloW** [comment]
Patching the drivers in order to get them running on PS Vita will be alot of work. Also, we won't be able to make use of any features, plus different devices and savestate is already available in Adrenaline Menu.
