### ISSUE TITLE
Adrenaline will not run after a ISO/Game Crash

### ISSUE THREAD

**Issue by Smoker1** [TheOfficialFloW/Adrenaline#129]
If a Game or ISO Crashes and you are able to Exit out of adrenaline, when you try to Launch it again, Adrenaline will just hang in a Black Screen after the Adrenaline Logo. You have to do a full Shutdown->Restart to get it to work again

**Comment by mathieulh** [comment]
That's because the pspemu itself (or the psp's kernel) crashed which makes the allegrex r4000 cpu unresponsive from the Vita side. I would assume it could be forcefully reset and this would fix the issue, I just don't know how.
