### ISSUE TITLE
CSO files cause crash

### ISSUE THREAD

**Issue by rootyElf** [TheOfficialFloW/Adrenaline#131]
When I've got a CSO file in /ISO Adrenaline gets stuck and I get C1-2858-3. This does not happen, if the game is on in ISO format.

The game I used was Ridge Racer 2. It was compressed using pspshrinker on level 5.

This error appeared in Adrenaline version 6. Older versions did not have this issue.

**Comment by TheOfficialFloW** [comment]
Can you send me the game?

**Comment by beps1** [comment]
I think I'm having the same problem. 
When there's a CSO file in /ISO, Adrenaline freezes just trying to list the games on the memory stick.
I'm using a PSTV with USB redirection, if that helps.

**Comment by TheRadziu** [comment]
Same issue on fat vita with location set to uma0. 
When I try to browse Memory Stick under GAME adrenaline just freezes, and after less than a minute it crashes with C1-2858-3 error. I only have CSO files in my /ISO folder. There was no issue like that on the previous version.

**Comment by rootyElf** [comment]
Also, when I try to start Adrenaline after it crashed, it gets stuck and crashes on boot. I have to restart my Vita to be able to start Adrenaline again.

**Comment by TheOfficialFloW** [comment]
https://github.com/TheOfficialFloW/Adrenaline/commit/20c0053cbb3816a6e452f8cdd2ef4da38d123273

**Comment by rootyElf** [comment]
Thanks
