### ISSUE TITLE
USB connection doesnt work with uma0 set as memory stick location / wrong mount with vita mem card as uma0

### ISSUE THREAD

**Issue by TheRadziu** [TheOfficialFloW/Adrenaline#133]
If "uma0:pspemu" is selected as memory stick location you can't use usb connection, it errors out with the message:
> An internal error has occured. (80244112)  

And nothing is mounted/connected on PC side.

If "ux0:pspemu" is selected as memory stick location, but user has SD card mounted on ux0 (original vita mem card as uma0), original memory card(uma0) is mounted instead. 
(Vitashell has exact same issue btw)

**Comment by weaknespase** [comment]
VitaShell don't have this issue - "Game card" option added recently, but it seems to be rather tricky to determine which device plays "ux0" or "uma0" role at any given time, so why not just having an option in settings to specify which device to mount?

**Comment by JacobMrox** [comment]
I'm getting this error too, I have sd2vita mounted as ux0 and memory stick location is ux0:pspemu
`An internal error has occured. (80244112)`

**Comment by Smoker1** [comment]
Not sure how, but on 1 Vita, I get this Error, but on my 3G Vita, I dont.......and it connects via USB, but shows everything in ux0 instead of the SD2Vita for PSPEMU.
Only thing that is different is my 3G Vita has the ux0 in the PSVSD.

**Comment by TheOfficialFloW** [comment]
Fixed in https://github.com/TheOfficialFloW/Adrenaline/commit/3352186d332891770343865149a05f6d27a717b0
