### ISSUE TITLE
Adrenaline6 freezes when CSO image is in ISO folder

### ISSUE THREAD

**Issue by tenow** [TheOfficialFloW/Adrenaline#134]
Adrenaline 6 freezes for 20 seconds and then crashes with error c1-2858-3 when there are CSO games in ux:pspemu/ISO/ folder

**Comment by TheOfficialFloW** [comment]
https://github.com/TheOfficialFloW/Adrenaline/commit/20c0053cbb3816a6e452f8cdd2ef4da38d123273
