### ISSUE TITLE
Can't run legitimately purchased PSN games with v6-fix

### ISSUE THREAD

**Issue by thedax** [TheOfficialFloW/Adrenaline#139]
My console hasn't been deactivated (I keep it offline, and I have a Vita-side plugin that prevents the activation files from being deleted), so that isn't the issue.

When trying to launch legally purchased PSN PSP titles, they all fail with "The game could not be started. (80010087)." 

I tried all UMD ISO modes and NoDRM on/off, to no avail.

These games also run fine from the Vita LiveArea.

List of games tried (all USA region): 
* TalkMan Travel Tokyo
* UNO
* Urbanix
* Monster Hunter Freedom Unite

These games all boot without issue in 5.1.

**Comment by TheOfficialFloW** [comment]
Hm I made a stupid change in v6. To fix it, just copy act.dat from tm0:npdrm/act.dat to ux0:app/PSPEMUCFW/flash2/act.dat

**Comment by thedax** [comment]
I'll give it a try and report back, thanks for the prompt reply!

**Comment by thedax** [comment]
That worked, thanks!
