### ISSUE TITLE
Crash in Adrenaline of any type causes all apps on Vita not working till reboot. 

### ISSUE THREAD

**Issue by shale1337** [TheOfficialFloW/Adrenaline#14]
1. Trying to use popsloader v4i crashes Adrenaline and only doulbe Home click works. After that none of apps for Vita working (Vita shell, Molecular shell, homebrew apps).
2. Faulty plugins that hang XMB create same kind of crash. (For example CXMB with bad theme that has problems with boot animation, Sony logo)
3. Some crashes were caused by using POPS plugins like TempAR_pops and CWCheatpops that are not working as well. 

It feels like these kinds of crashes actually crash Henkaku as well.

Full reboot helps.

**Comment by julienkoenig** [comment]
i have the same problem, i've learned, if i wait till an error pops up and the application closes itself, then i can most of the time use the other apps like vitashell and so on..

**Comment by apizzamra** [comment]
the flow already said that popsloader wont be supported on adrenaline 

but yeah, if some error happen inside adrenaline it will mess up the henkaku apparently
