### ISSUE TITLE
PSTV running latest Adrenaline6fix PS1 screen mode not working & official settings no screen mode options 

### ISSUE THREAD

**Issue by Capoceo** [TheOfficialFloW/Adrenaline#143]
A quick thanks to you for your work and the idea of sharing it to the world! I am running into a issue where i cannot change the screen size settings for ps1 aka psx games. Firstly my PSTV is running without a act.dat yet my signin info is still saved. I installed the latest adrenaline as instructed per your info and everything was successful. Have no issues with my personal ISO's and homebrew. Only issue is any ps1 game i launch the game screen size is small and moved to the top left corner of the actual TV. Adrenaline's screen mode has no effect, and with the official settings there is no options for screen settings as there should be just like on a psvita. only thing i noticed was when choosing official settings while the ps1 game is running is the that the screen switches from what i can tell to original  but when i close out of the official settings it goes back to the upper left side of the screen. I don't want to make any assumptions i'll leave the experts to their solutions thanks!

**Comment by TheOfficialFloW** [comment]
Look at Adrenaline Menu.
