### ISSUE TITLE
Adrenaline freezes up

### ISSUE THREAD

**Issue by robmccoy93** [TheOfficialFloW/Adrenaline#144]
It freezes up completely and won't work even after waiting a while, when I click on the games tab after opening adrenaline. I tried reinstalling it. I tried restarting the app. I tried restarting my vita. I am using SD2VITA v3, mounted as ux0. It's odd because ARK can run games just fine. also, yes i'm using the adrenaline v6-fix.

**Comment by magub93** [comment]
I tried it for some time and it seems that cso format games in ISO folder cause this freezes to happen. So just dont use cso until it get fixed.

**Comment by ysmin7** [comment]
I also have same issue with yours. And environment is also exactly same with you.

**Comment by ysmin7** [comment]
It's a because of cso files.

**Comment by patrickmau** [comment]
I can dito this, i am experiencing the same problem. Adrenaline freezes when trying to show the games on the memory stick, but only if there is a CSO file inside /pspemu/iso/. I also get a C1-2858-3 error after some time, after which Adrenaline force closes and kicks me back to the PS Vita home screen. When trying to reopen the Adrenaline bubble, I get another C1-2582-3 error preventing Adrenaline from starting again, forcing me to restart the Vita before I can open Adrenaline again.

I am running on 3.60 Henkaku + Enso + Adrenaline 6.61-6.

**Comment by TheRadziu** [comment]
@patrickmau update to v6 fix. If problem persists make a clean reinstall.

**Comment by patrickmau** [comment]
@TheRadziu as said, I am running v6-6 already, and have reinstalled several times. On a note, all CSO files were created via UMD-Dump which other users use in their CSOs as well but experience no problem.

**Comment by MKesenheimer** [comment]
Same problem here. I am using v6-6 with sd2vita and Adrenaline freezes when loading a *.cso file. After the crash, I have to reboot the vita and reinstall Adrenaline completely in order to make Adrenaline work at all.

**Comment by darkenvy** [comment]
Same problem;
PSTV running usbmc 256gb flash drive as ux0.

I discovered it was CSOs crashing adrenaline and did a search to find this ticket.
