### ISSUE TITLE
No Game/ISO titles when using GC Lite 1.6

### ISSUE THREAD

**Issue by VorgonBattlecruiser** [TheOfficialFloW/Adrenaline#145]
When using Game Categories Lite 1.6 by Codestation i am no longer able to see the titles of my Isos/CSOs and PSX games.

**Comment by rsn8887** [comment]
Same here.

**Comment by IcySon55** [comment]
It's working perfectly fine for me.
Use CAT_ = Yes
Sort Categories = No (I sort them using the Homebrew Sorter instead)

**VSH.TXT with the 1.6 plugin:**
ms0:/seplugins/category_lite.prx 1

**Directories:**
pspemu\ISO\CAT_RPG\files.iso
pspemu\PSP\GAME\CAT_Homebrew\Homebrew Sorter\EBOOT.PBP
pspemu\PSP\GAME\CAT_PS1\folders\EBOOT.PBP

Just in case your version is a variant that doesn't work:
[category_lite_v1.6.zip](https://github.com/TheOfficialFloW/Adrenaline/files/1301883/category_lite.zip)

**Comment by rsn8887** [comment]
@IcySon55: Your version works fine. The filesize of your category_lite.prx is different than my original one, too.

**Comment by rsn8887** [comment]
I think this issue should be closed, because it works fine now with the correct category_lite file that IcySon55 provided.

**Comment by VorgonBattlecruiser** [comment]
I attempted changing the settings and using the version supplied by IcySon55, yet nothing changed.
Adapted my folder structure, tried different settings (and reloading VSH), yet the issue remains.
This, sadly, did not fix it for me.

**Comment by IcySon55** [comment]
You must have missed something since it works for me and also fixed it for @rsn8887. Double check everything again.

**Comment by melterx12** [comment]
ok, here was my issue, I hope this clears up some confusion: 

I am using sd2vita as my secondary storage (uma0) in addition to the regular memory card (ux0). Now, if you change the adrenaline "Memory Stick Location" setting to whatever you are using as the secondary storage (in my case, uma0), make sure you move the seplugins folder into that directory as well! Otherwise, your plugins will not load.

**Comment by VorgonBattlecruiser** [comment]
I have SD2Vita set as ox0, renamed my category-folders with the prefix "CAT_",replaced my category lite plugin with that posted by IcySon55, turned the category-setting on in the psp settings and checked my plugin txt-files.
I use pprefs to sort my games.
I did everything according to prior posts and no change whatsoever.
I honestly have no clue what i am missing here.

**Comment by meoow** [comment]
Same issue here.  
**Adrenaline version: 6.9  
GC Lite version: 1.6  
(category_lite.prx md5: 5fa203859237410846db2284f9fac384)**

It only works for homebrews and PSOne games inside _/PSP/GAME/CAT\_\*_ .  
No titles inside inside _/ISO/CAT\_\*_ can be seen from XMB.
