### ISSUE TITLE
An issue with the Vita TV and charging

### ISSUE THREAD

**Issue by deadair3210** [TheOfficialFloW/Adrenaline#146]
First, thanks  for all that you have made for the vita, especially this. My only problem right now is that the emulated PSP constantly thinks its being charged on the Vita TV, and seems to stay at around 75%. This affects games like Rengoku that show the system battery status in the game.

Would there possibly be a way to either change the emulated state. or something to that effect?

**Comment by kozarovv** [comment]
Try use FX Powerspoof v0.3 plugin (at psp plugins, not vita/pstv).

If not work try additional 6.60 to 6.61 plugin by Davee.
