### ISSUE TITLE
Adrenaline won't boot up after shutdown PSvita and rerun henkaku

### ISSUE THREAD

**Issue by apekingmeister** [TheOfficialFloW/Adrenaline#147]
Step i face issues  i tested by 

PS vita 1000  3.60 hen + Adrenaline 6

1- install henkaku + offline hen  =  working fine
2- install adrenaline  = working fine
3- shutdown vita   
4- power on
5- install henkaku offline = working fine
6- run adrenaline =  **not working**
7- try running adrenaline 4-5 time just popup and then back to start screen from icon ( not show adrenaline boot screen logo yet) 
8- reinstall adrenaline  and rerun = not boot
9- delete all Adrenaline relate file ( from icon and check from vita shell ux0/app)  
10- reinstall  adrenaline = working

: So Question = Do we have to install adrenaline again every time we shutdown PSvita or reinstall Henkaku  on this version 6 ?  or is it just my PSvita is messed up  then i will format and try again then report the result

**Comment by marvin-SL** [comment]
same for me

**Comment by LIxusKH** [comment]
I opened a lot a of times until it crashed and the ps vita reboot again, i hit the bubble two times and it wored like nothing to me
