### ISSUE TITLE
Unable to install psp 6.61 firmware

### ISSUE THREAD

**Issue by Dimensional** [TheOfficialFloW/Adrenaline#148]
I'm currently using the latest V6-Fix. I followed the instructions to delete my Adrenaline folder and remove Adrenaline from my config.txt file before uninstalling the old Adrenaline, and then installed the new version. The new version constantly has an issue trying to download the firmware, giving error 0x80436003 code. I tried bypassing this by just downloading the eboot.pbp file from playstation.com, but then it give code 0x80410136. Changing the file name allows the program to run it's first time, but the second required time crashes with C1-2738-0.

**Comment by kozarovv** [comment]
80436003 is DNS error. Make sure you don't use proxy for download time. Also check that happen with other DNS server, henkaku one, or google dns. 
80410136 is SCE_NET_ERROR_ECONNRESET that is suggesting network problem, or IP ban. 

About C1-2738-0 is only my assumption, but did you downloaded correct eboot.pbp? MD5 of it should be: 6BE8878F475AC5B1A499B95AB2F7D301

NOT: fd0f7d0798b4f6e6d32ef95836740527 which is psp go 6.61 fw.

**Comment by Dimensional** [comment]
I'm finding it hard to believe my own network, which I manage, is somehow blocking my vita since it's not set up to do that. And the MD5 matches.

**Comment by shinji257** [comment]
Not sure what the issue is here but I do want to point out that the henkaku dns doesn't block the psp download as I use that to prevent any vita updates past 3.60.

**Comment by Dimensional** [comment]
I don't even have my DNS configured to block Vita updates. I simply just don't auto download/install them.

**Comment by Dimensional** [comment]
Okay, I managed to get past the install of the 661.pbp file. I uninstalled the app through Content Manager, then reinstalled it through Vitashell. AFter that, I copied the firmware file to the app folder without overwriting or deleting the 104 byte eboot.pbp file already there. After that, it finally installed and I'm confirming I can access even after rebooting the Vita.
