### ISSUE TITLE
Adding "adrenaline_kernel.skprx" to *KERNEL prevents Adrenaline to boot

### ISSUE THREAD

**Issue by Recchi** [TheOfficialFloW/Adrenaline#149]
After uninstalling the old Adrenaline (removed the kernel and basegame entry from config.txt + deleted the adrenaline folder and the basegame then rebooted) and installing the new one (including 661.PBP) Adrenaline booted successfully. 
Starting the Adrenaline bubble twice would be OK with me, but the first one must be with unsafe homebrew enabled, which I like keeping disabled. To circumvent this I followed the instructions in the readme and added "ux0:app/PSPEMUCFW/sce_module/adrenaline_kernel.skprx" under *KERNEL in my config.txt. 
After rebooting and trying to fire up adrenaline with unsafe homebrew disabled it tells me to enable unsafe homebrew and when I enable it it shows the same message it is supposed to shows when you don't uninstall the old Adrenaline (something along the lines of it unable to load adrenaline_kernel.skprx and that I should uninstall the old one first). 
Commenting the line out in config.txt and rebooting makes it work again, but of course it has to be launched the first time with unsafe homebrew enabled.
After uninstalling and reinstalling it a few times (also trying the non-fix version of Adrenaline-6, which behaves even worse: with adrenaline_kernel.skprx in config.txt it just simply kicks me back to menu indefinitely without any messages) the problem persists.
As I did not find anyone on the internet with the same problem, the question is: is it just me or no one bothered adding adrenaline_kernel.skprx to config.txt?
Also I'm on a Slim Vita if it helps. Thank you very much for your kind reply in advance.

**Comment by shinji257** [comment]
I added the line and it works fine here with a slim vita.  I also have unsafe homebrew enabled.  Maybe try with unsafe enabled and boot with the line in the config file?

**Comment by Recchi** [comment]
Tried it, same thing happens. Also I forgot to mention that I'm not using Enso (I like to play it perfectly safe), but the offline email trick to load taiHENkaku. Could that be the problem/does that make a difference?

**Comment by apekingmeister** [comment]
i think i'm on same issues  but i cant describe in technical words much, it just cannot start take back to start screen al the time   

I'm gonna try enso to night and see if any different from offline email trick

**Comment by Phoenix09** [comment]
I'm having this problem too.
I already removed all traces of adrenaline and did a clean install of henkaku, adding that line still breaks adrenaline

**Comment by gensosuikoden** [comment]
Greetings, people. I can confirm that (at least in my experience) the issue was confined to regular/temporary Henkaku. I just now upgraded to Enso and the fix in question now works for me as advertised.

**Comment by TheOfficialFloW** [comment]
Fixed https://github.com/TheOfficialFloW/Adrenaline/commit/c6804e16e7231001af35dcc98dedc5a9f9bdf645
