### ISSUE TITLE
Vita Memory Card on uma0  - immediate crash on opening "memory stick"

### ISSUE THREAD

**Issue by chaoskagami** [TheOfficialFloW/Adrenaline#150]
When a vita memory card is mounted as uma0, and you use this as the pspemu device, if there is even a single game in either PSP/GAME/ or ISO/, the spinner in the bottom will lock up and the entire system will freeze, followed by a C1-2858-3 error and a need to reboot for any PSP game to function.

This doesn't seem to happen using ux0 normally or ur0 as far as I can tell.

This also doesn't happen when opening "memory stick" on the photos or videos categories.

**Comment by TheOfficialFloW** [comment]
Are you using the v6 fix?

**Comment by chaoskagami** [comment]
Yes. I wouldn't have filed a bug report unless I'd checked to make sure.

**Comment by chaoskagami** [comment]
So I'm annoyed at myself now for being a moron; due to my Downloads folder being so disorganized, I apparently labeled the file wrong and installed v6, not v6-fix.

Closing for own idiocy. Sorry. :/

**Comment by devtekve** [comment]
@TheOfficialFloW I can confirm that this issue is still happening.
