### ISSUE TITLE
Adrenaline just exits back to home screen after downloading/installing 661.PBP

### ISSUE THREAD

**Issue by DJ-RK** [TheOfficialFloW/Adrenaline#154]
Had Adrenaline installed about a month back using the PSP Mini game method, but unfortunately not only has my memory card just completely killed itself, but now apparently I can't download off the PSN anymore (even though I'm sure my Vita was activated)... but all that's a different matter than what I'm currently facing.

Anyway, now I'm trying the new Adrenaline.vpk method. When I load it up, it says the 661 firmware is not installed and needs to be downloaded. Once it finishes downloading the app just exits back to home screen, and every time trying to reopen it, it will just kick right back. Tried uninstalling, reinstalling, and even copying the 661.PBP over to the install folder, and same thing happens.

Any solutions?

Edit: If it matters, I'm running from ux0 on a SD2Vita card.

**Comment by TheOfficialFloW** [comment]
Reboot.

**Comment by DJ-RK** [comment]
Thanks for responding so soon. I had forgot to mention that rebooting was the first thing that I had tried. I left my Vita in my truck at work tonight, but when I bring it home tomorrow I'll try unmounting the SD2Vita and installing it to an official memory card on ux0, since I suspect that may be what's causing this (unless you have reason to believe otherwise).

**Comment by Smoker1** [comment]
Basically you need to remove EVERYTHING Adrenaline Related. 
Keep a copy of 661.PBP, you will need it.
Install the Adrenaline Fix VPK
Move the 661.PBP to
ux0:app/PSPEMUCFW/
In the config.txt in the ux0:tai Folder, go to where it shows
ux0:adrenaline/adrenaline.skprx 
and change it to
ux0:app/PSPEMUCFW/sce_module/adrenaline_kernel.skprx
Reboot
Run the Adrenaline App and follow the Instructions. Should work like a charm.

**Comment by DJ-RK** [comment]
That did it. Thanks for the help.

**Comment by Banhmitrung84** [comment]
Hi all, i do all the step and it still back to home screen. I try it 10 times and nothing work. Please help.
