### ISSUE TITLE
Memory Card Utility issue?

### ISSUE THREAD

**Issue by darkfoxus** [TheOfficialFloW/Adrenaline#16]
First of all, thanks for this massive improvement, V3 is awesome. However I’m concerned with the Memory Card Utility. 

I’m trying to import a save data from PC (mcr format) inside the vita but I’m being unable to do so. Sadly, the standard way of doing it can’t be used as loading cwcheat plugin in psone mode doesn’t seems to be working.

My question is, Can’t the Memory Card Utility achieve that?, can´t  it be extended to copy individual ps-one files not just between slot 1 and 2 but also from a mcr file in the SD?
Finally, I can’t support you with money, but if I’m pointed in the right direction, I might be able to support you with code. Thanks again for the awesome work.

**Comment by TheOfficialFloW** [comment]
No
