### ISSUE TITLE
Adding support popsloader on adrenaline (feature request)

### ISSUE THREAD

**Issue by iOS4all** [TheOfficialFloW/Adrenaline#160]
We all know adrenaline is so great and bring full psp stuff and extra amazing features like filters and savestate. We just missing popsloader support on adrenaline to be most complete edition of it.
The last time we saw support of popsloader was on TN-X.
Thanks.

**Comment by TheOfficialFloW** [comment]
There was no popsloader for TN-X wtf...are you dreaming or wat. Not possible lol

**Comment by iOS4all** [comment]
Oh My bad. I'm sorry I was thought tn-x had popsloader.
Anyway thanks
