### ISSUE TITLE
C0-15012-9 issue

### ISSUE THREAD

**Issue by KratZ88** [TheOfficialFloW/Adrenaline#161]
Hi, please help me, 

I keep getting this error when I try installing 661 adrenaline vpk and the installer will force close. I have henkaku enso installed and sd2vita 64gb which I use as internal memory.

**Comment by kozarovv** [comment]
Probably your file system is corrupted, or/and you are using cheap mSD card. Copy your files somewhere, then prepare card again for use with sd2vita (linux mkfs.exfat method, or windows zzblank image method), and recopy your files to it. Then try to install adrenaline again.

**Comment by KratZ88** [comment]
Ok I will try to restart the whole step again, but I don't think my msD is the problem though. I am using SanDisk class 10 64gb

**Comment by KratZ88** [comment]
Thought I will share how I deal with this problem, I just keep restoring the system until I am able to install the adrenaline using vitashell without any errors.

But everytime I restore the system, I need to reinstall HENkaku.
