### ISSUE TITLE
CSO breaks loading

### ISSUE THREAD

**Issue by svennd** [TheOfficialFloW/Adrenaline#165]
I copied a CSO in /ISO folder this causes adrenaline to hang when trying to create a list, eventually it crashes with a generic error.  After that adrenaline only wants to show a black screen. A system reboot is required to start adrenaline once more.

The workaround seems to be to decompress the CSO to a ISO file.

**Comment by eadmaster** [comment]
same problem here ISO games are working fine, CSO don't.
Probably there are some compression options that are unsupported?
Which tool/options do you suggest to use to CSO compressio?

**Comment by svennd** [comment]
I have no idea, those games are pretty old already. If there is a way to compress them in the "right format", I would like to know.

**Comment by Yuki-nyan** [comment]
I am having the same issue on the latest Adrenaline-6 and also having no problems with ISO games. My CSO files are compressed with maxcso (https://github.com/unknownbrackets/maxcso/releases). In case it makes any difference, my ux0: is on a 200GB micro SD via an internal psvsd adapter.

**Comment by patrickmau** [comment]
Dito, same issue here as well. Any advice on how to best decompress a CSO to ISO? I have a lot of CSO's on  my HDD and would prefer to not keeping ISO and CSO versions of the same game just to work around that bug...

**Comment by thrasherht** [comment]
Confirmed I have the same issue. I decompressed the CSO into an ISO and it works fine, but as a CSO it causes adrenaline to crash.

**Comment by noxiousninja** [comment]
I have all my PSP games as CSOs, and haven't had any problems.  I used [UMDGen v4.00](https://www.romhacking.net/utilities/1218/) to compress them.  Haven't tried any other tools.

**Comment by TheOfficialFloW** [comment]
https://github.com/TheOfficialFloW/Adrenaline/releases/tag/v6_fix
