### ISSUE TITLE
when psx games start, plugins are disabled

### ISSUE THREAD

**Issue by theheroGAC** [TheOfficialFloW/Adrenaline#168]
I would like to point out the problem of plugins that are disabled just as you start a psx game.Thank you

**Comment by dude22072** [comment]
Are you talking about PSP plugins or PSV plugins?

**Comment by theheroGAC** [comment]
PSP plugins

**Comment by dude22072** [comment]
PSP has always had separate plugins for PS1 games, contained in the POPS.txt file in the plugin folder.

**Comment by theheroGAC** [comment]
Yes POPS.txt(not work) for PSX,Vsh.txt and GAME.TXT
