### ISSUE TITLE
Bug in Burnout Legends Adrenaline V3

### ISSUE THREAD

**Issue by Dragda** [TheOfficialFloW/Adrenaline#17]
After updating from the V2 to the V3, i have discover an error after launching the psp game Burnout Legends. 
Afer the first "loading" screen, it goes to black and the system shows an "Please wait" message. After that i can't exit the game, show the adrenaline menu... anything. I have to softreset the console every time.  Tried with another games like Patapon 2 and Flow, and works perfect. Only shows the error with the Burnout.
The weird thing is that the game was working perfect with the V1 and V2; in fact i reversed to the V2 and works again well.

**Comment by Rufis01** [comment]
Same, I'm using a ISO tho

**Comment by TheOfficialFloW** [comment]
Fixed here https://github.com/TheOfficialFloW/Adrenaline/commit/b64d2d11cc4602ac8731e21158d4e8bd53896399
