### ISSUE TITLE
Mhz not at 333 when I start Games as Bubble even though it's set in Adrenalin?

### ISSUE THREAD

**Issue by Zeitwaechter** [TheOfficialFloW/Adrenaline#173]
Hey there!

First, I also want to express my gratitude to this amazing combination of features.

Second, this is an follow-up issue in reference to another issue but in the [ABM repo](https://github.com/ONElua/AdrenalineBubbleManager/issues/16).

The problem is that any ISO-/CSO-Game that I "installed" through _AdrenalineBubbleManager_ won't be run at 333Mhz even though I set it to 333MHz in Adrenaline-6-fix - it's at 200MHz instead.

You can find/test this behaviour when starting _Dragon Ball Z - Tenkaichi: Tag Team_ from `uma0:` on a 64GB Sony Memory Card while also run pspemu/Adrenaline from `uma0:`.
Notice: Yes, `ux0:pspemu` (sd2vita) is not used, Adrenaline runs under `uma0:pspemu` (Sony MC) and the ISOs are also located there.

Summarized: It won't run at 333MHz when started via ABM-Bubble from the Vita XMB unlike when started via the Adrenaline PSP XMB.
Also it's possible to start the Game via ABM-Bubble, return to Adrenaline PSP XMB via Home-Button only to start it there again to run at 333MHz.

As the maintainer of _AdrenalineBubbleManager_ stated to me that this is not his fault I came to seek help in this repo first before opening another issue in Lmans' related repo, as that person seems to be the origin of the feature/framework/adapter-bridge.

Thank you very much in advance.

Greetings :)

**Comment by gensosuikoden** [comment]
Happy New Year.

Were you able to find a work around? If not, respond to this post and I will advise (am not a dev but have found two workarounds).

**Comment by Zeitwaechter** [comment]
Hi there - Happy New Year to you too.

Sadly I never got a useful reply here and found no workaround elsewhere.
So it's still happening and I'm waiting for any tip on how to "fix" it :)

**Comment by gensosuikoden** [comment]
Ok, I'll try and help.  A few questions so I know exactly where you are at. Please itemise your answers as I have done the questions.

1. When you say you have Adrenaline installed on uma0 you mean that the Adrenaline folder tree (PSPEMU), games, saves, seplugins etc. are on uma0 but your primary memory card for Vita is still the official ux0, correct? 
If so, for future reference, that means that as an app, Adrenaline is still installed on and running from your ux0, just some of the data (games, saves, seplugins etc.) are on uma0. That would mirror my set-up: I have all my Adrenaline ISOs, save games, seplugins etc. on uma0, but, my official Sony memory card is still my primary storage (ux0) and the core Adrenaline files are installed on it accordingly (ux0:app/PSPEMUCFW/). 

2. When you say you are setting the clock to 333mhz from the Adrenaline XMB, what exactly do you mean / how are you doing this? Are you pressing start + select and then changing the speed in the VSH menu?

3. Once you've launched a game either from a bubble or from the Adrenaline XMB, how are you checking the clock speed in-game? AFAIK pressing start + select doesn't bring up the VSH in-game unless you have the PSPCFW 'Satellite' plug-in installed and activated. Do you have this plug-in installed/activated?

**Comment by Zeitwaechter** [comment]
I'm sorry for beeing out of the loop for so long!

I will try it again to make sure things are still the same.

**Comment by Zeitwaechter** [comment]
So, even after setting everything to 333/166, it does still seem that CSO-files are way to slowly read on Vita than on PSP.

Anyways, let me confirm some things:

1. Yes, `PSPEMUCFW` is still on `ux0`. `pspemu' is on `uma0`, though.
So in the end `ux0` is still the primary memory card.

2. Is did set `333`/`166` via `VSH menu` and `cw cheat`.

3. Pressing `Select` + `Start` doesn't do anything.

---

4. Enso isn't showing the `HENkaku Settings` in the settings menu anymore.
I recently found out that there is a trick to it, to reinstall Enso.. but it doesn't seem to work due to a mismatch in `os0` of the checksum. Meh. 
(Known HENkaku FW3.65 settings bug)

Greetings :)
