### ISSUE TITLE
C1-2858-3 can't access my adrenaline games after it freeze

### ISSUE THREAD

**Issue by rm11ksk** [TheOfficialFloW/Adrenaline#175]
It work fine at first with 20gb games inside (iso and cso), then my adrenaline freeze after i tried to fill a 30gb games into it and it stuck, i then restart it with the power button until i found a message of C1-2858-3 show up everytime i tried to access the games folder in adrenaline

I tried to fix it with reboot vita and reinstall the adrenaline, delete some games and all the cso games until only 10gb games left but C1-2858-3 still show up

I use already use the latest adrenaline 6-fix in sony memory card 32 GB as uma0

- sorry for my broken english

**Comment by rm11ksk** [comment]
Update :
I tried to test load a game from uxo (sd2vita) and it work fine

But the problem keep the same for uma0 (sony memory card)

**Comment by TheOfficialFloW** [comment]
hard to fix
