### ISSUE TITLE
BURNOUT LEGENDS

### ISSUE THREAD

**Issue by oneiros1984** [TheOfficialFloW/Adrenaline#177]
Hi

I cannot play an ISO of Burnout Legends. The NTSC version does not load at all. The PAL version hangs on the loading screen. 

This appears to be a common issue and is usually fixed by turning Auto UMD off and/or switching to NP9660. 

None of that works. I also have a legitimately purchased version in the PS Store but it will not activate or download.

Please assist.

**Comment by noxiousninja** [comment]
Are you sure you have good dumps?  The game seems to work for me.  I just tested all 3 USA releases, and was able to load and play each:
- [Original release](http://datomatic.no-intro.org/index.php?page=show_record&s=62&n=0140)
- [Greatest Hits release](http://datomatic.no-intro.org/index.php?page=show_record&s=62&n=1457)
- [PSN US release](http://datomatic.no-intro.org/index.php?page=show_record&s=91&n=0341)

I ran all of them as CSOs.  For the physical releases, I compressed the ISOs to CSOs with [UMDGen v4.00](https://www.romhacking.net/utilities/1218/).  For the PSN release, I converted the PKG to an ISO with [PSN PKG Decryptor & Extractor Written By LMAN v1.85](https://sites.google.com/site/theleecherman/psnpkgdecryptor-extractor), then compressed the ISO into a CSO with UMDGen.

For Adrenaline, I used the version from [Adrenaline Bubble Booter VPK Edition v0.1](https://sites.google.com/site/theleecherman/adrbubblebooter/vpkedition) with the Inferno engine.

**Comment by oneiros1984** [comment]
I downloaded the Platinum release and it’s working perfectly 😎
