### ISSUE TITLE
Error C1.2858-3 with SD2Vita 6.61 Adrenaline-6

### ISSUE THREAD

**Issue by nussbam** [TheOfficialFloW/Adrenaline#179]
My Vita (Model PCH1004) is currently running Henkaku Enso. I bought a SD2Vita adapter, which seems to work fine, since I can access it over VitaShell and molecularShell. Additionally I can play Vita-Games I downloaded onto it.

I installed Adrenaline-6 and the process worked so far. I can open the application without issue, I can open my games under uma0: and play them, but as soon as I try to access my games under: ux0:pspemu I get an C1.2858-3 error.

My config file under ur0:tai is like this:
`# This file is used as an alternative if ux0:tai/config.txt is not found.`
`# For users plugins, you must refresh taiHEN from HENkaku Settings for`
`# changes to take place.`
`# For kernel plugins, you must reboot for changes to take place.`
`*KERNEL`
`ur0:tai/gamesd.skprx`
`# adrenaline loads after the microsd has been loaded as main storage`
`ux0:app/PSPEMUCFW/sce_module/adrenaline_kernel.skprx`
`# henkaku.skprx is hard-coded to load and is not listed here`
`*main`
`# main is a special titleid for SceShell`
`ur0:tai/henkaku.suprx`
`*NPXS10015`
`# this is for modifying the version string`
`ur0:tai/henkaku.suprx`
`*NPXS10016`
`# this is for modifying the version string in settings widget`
`ur0:tai/henkaku.suprx`

Any help would be appreciated

**Comment by rm11ksk** [comment]
How many game you have installed?

**Comment by nussbam** [comment]
Currently there are 3 vita games and like 4 PSP games on the psp

**Comment by Orangemike80** [comment]
I had the same issue, even though I had it working on another Vita, then I noticed the only difference was on the one with the error I had games that were .cso and these caused the error I removed these games from the ISO game folder and it worked fine, I then converted the .cso to .iso files then those games worked, not sure if you can have a CSO game folder or not?? Hope this works for you.

**Comment by TheOfficialFloW** [comment]
Are you guys sure you're using the v6 fix? https://github.com/TheOfficialFloW/Adrenaline/releases/tag/v6_fix
