### ISSUE TITLE
USB Connection Non-Functional

### ISSUE THREAD

**Issue by slickrasta** [TheOfficialFloW/Adrenaline#180]
In v5 I was about to connect my Vita via USB Connection mode to my PS3 to transfer owned PSN titles easily to it. This function seems to be broken all together in v6fix when you select it it immediacy esays USB Mode and a normal PSP would load a bit before that comes up to show it is connected. Any chance this can be fixed or was this sacrificied as part of the vpk install version?

**Comment by slickrasta** [comment]
*immediately says

**Comment by dude22072** [comment]
See issue #63 
According to FloW, USB support is not an option.
