### ISSUE TITLE
C1-2858-3 error when loading games. Using SD2Vita, 6.61 Adrenaline-6, Henkaku manual

### ISSUE THREAD

**Issue by jepoyeng** [TheOfficialFloW/Adrenaline#186]
I am using an SD2Vita adapter (version 3) and I am encountering a C1-2858-3 error whenever I press the Memory Stick option under the Game tab. I cannot load or start any games.

When I remove the .ISO file (around 1.2GB) inside the ISO folder, it doesn't crash. Only shows an error that the folder is empty. Adrenaline seems to run fine as it can detect my old save files I transferred from my PSP.

Here's the content of my ux0:tai/config.txt

===================================================

# For users plugins, you must refresh taiHEN from HENkaku Settings for
# changes to take place.
# For kernel plugins, you must reboot for changes to take place.
*KERNEL
# henkaku.skprx is hard-coded to load and is not listed here
*main
# main is a special titleid for SceShell
ur0:tai/henkaku.suprx
*NPXS10015
# this is for modifying the version string
ur0:tai/henkaku.suprx
*NPXS10016
# this is for modifying the version string in settings widget
ur0:tai/henkaku.suprx

=========================================

The contents of ux0:/pspemu are:

ISO
PSP
PSP/GAME
PSP/SAVEDATA

I placed a single ISO file inside the ISO folder.

I assumed that the SD2Vita is working since Adrenaline already runs. I've also enabled Forced High Memory layout in the Adrenaline recovery menu. I am running 6.61 Adrenaline-6.

**Comment by Skynet00** [comment]
Use the fix version of 6.61.
