### ISSUE TITLE
Issue with double tapping the PS button

### ISSUE THREAD

**Issue by Rodion4014** [TheOfficialFloW/Adrenaline#19]
After double tapping only this label appears

![error](https://cloud.githubusercontent.com/assets/18441750/25075245/553b11f4-233a-11e7-8d64-f05d6dd5c5b2.jpg)

It says - Could not find the application

**Comment by WanderMax** [comment]
please use fixed version of v3

**Comment by Rodion4014** [comment]
Thanks!
