### ISSUE TITLE
"Adrenaline v6-fix(ed version)" still requires double launch despite recommended edit to tai config.txt

### ISSUE THREAD

**Issue by gensosuikoden** [TheOfficialFloW/Adrenaline#193]
Hello, first of all, thank you for all your amazing work. You have revitalised my Vita! 

I am running the latest version of Henkaku (not Enso) on an OLED vita. "Unsafe homebrew" is enabled too.  I am unable to get rid of the double launch issue despite following all instructions. All traces of the previous Adrenaline  5.1 installation were uninstalled / removed (bubbles, files/folders, mentions in config.txt etc.) from both ux0 and ur0 prior to the installation of v6-fix. (I skipped the original v6 and went straight to the v6-fix vpk as I understand they are the same, aside from the fix.( I should add that I am not using SD2Vita. My only external memory is an official Sony 64gb Vita card. 

I added the following as instructed:

*KERNEL
ux0:app/PSPEMUCFW/sce_module/adrenaline_kernel.skprx

- to tai config.txt (the above is exactly how the two consecutive lines appear in my config.txt). But it  actually **_prevents_** adrenaline loading at all for me. With that line in place, trying to launch kicks me back to the home menu every single time. Same thing happens if I delete the ux0 config.txt and use the ur0 config.txt with the aforementioned line added too instead. On a few exceptions, I instead got the black screen / white text message: "Could not load_adrenaline_kernel.skprx. Please uninstall the old Adrenaline first."

 I should add that I have tried many reboots, total uninstall/reinstalls, several database rebuilds and have also removed all optional plugins (such as battery info, vita overclock and nonpdrm etc.) from their respective folders and any mention of them from the config.txt but the problem persists.

I saw a comment on one forum (gbatemp or wololo, can't remember) where the user claimed that he eliminated this very same problem just by switching to Enso. Perhaps that is the root of the problem, that I am on standard Henkaku? Regrettably, I am no comfortable switching to Enso yet, however small the risk might be so I'll make do as is until future releases. Launching twice is no deal breaker. 

In any case, it was just a heads-up and thank you once again for all your amazing work!

**Comment by gensosuikoden** [comment]
Update: I have now upgraded to Enso and can confirm that the fix in question now works for me so it would appear that the issue related to regular/temporary Henkaku only.

**Comment by TheOfficialFloW** [comment]
Fixed in v6.4.
