### ISSUE TITLE
Aspect ratio in PS1 “normal” mode is not wide enough

### ISSUE THREAD

**Issue by rsn8887** [TheOfficialFloW/Adrenaline#194]
EDIT: I tested this only with the two games “Lomax Adventures in Lemmingland,” and “N2O Nitrous Oxide” so it is possible that other games do not have this issue.

It seems there is a bug when playing PS1 games in Adrenaline using the Adrenaline gfx mode setting “original” (to force Vita to use official rendering) and official screen mode setting “normal.”

In that case, the game screen fills the Vita screen vertically as it should but it is not wide enough horizontally, e.g. the PS1 game aspect ratio is not 4:3 in this case. It can be observed by opening official settings while a PS1 game is running and switching the screen mode between original and normal. The screen then changes instantly and it is obvious that going from “original” to “normal” the screen stretches almost only vertically and not enough horizontally.

The aspect ratio is correct when using the official screen mode setting “original.” It is just the “norma” setting that shows this issue.

It seems like this is probably a bug in the Vita firmware itself, since it happens using just the official settings.

Could Adrenaline patch this problem with the firmware and force PS1 games to show the image with correct 4:3 aspect ratio even when using “original” in Adrenaline and “normal” in the official screen mode setting? I understand that setting Adrenaline mode to “bilinear” and Adrenaline PS1 Mode to “normal” gives the correct aspect ratio and picture size, but it also introduces slowdown and tearing in some games because of the computational overhead introduced when Adrenaline is doing its own filtering.

**Comment by TheOfficialFloW** [comment]
Official screen mode should be original anyways, otherwise you‘d double scale it

**Comment by rsn8887** [comment]
Yeah I don't even understand what I was trying to say here anymore.
