### ISSUE TITLE
adrenaline error files corrupted 

### ISSUE THREAD

**Issue by Play240** [TheOfficialFloW/Adrenaline#198]
I have a ps vita fat with the last version of adrenaline installed but it doesn't read the isos, it only says corrupted files when i try to open them. For being sure i even cheched the isos with SHA1 and they are intact. I doubled cheched the isos folder that is ux0:pspemu/PSP/GAME/ISO. Any answer?

**Comment by TheOfficialFloW** [comment]
Filename too lang maybe
