### ISSUE TITLE
Small screen size on Playstation TV

### ISSUE THREAD

**Issue by typhfox** [TheOfficialFloW/Adrenaline#200]
When I load a ps1 game on Adrenaline on Playstation TV, it runs perfectly but the screen size is very small. I tried to change all the Adrenaline's screen options to expand it but nothing works. It only happen with ps1 games, PSP hombrew and games works great. Thanks and keep it up the good work!
![image](https://user-images.githubusercontent.com/10656632/34757141-11378158-f5ae-11e7-8792-f6d58d9db65d.png)

**Comment by Catarax** [comment]
Use any mode instead of Original and you can adjust the size on latest adrenaline for pstv.
