### ISSUE TITLE
(C1-2858-3) Error on some games (6.61 Adrenaline-6 fix)

### ISSUE THREAD

**Issue by tibyandy** [TheOfficialFloW/Adrenaline#201]
Just like reported by [issue 192](https://github.com/TheOfficialFloW/Adrenaline/issues/192), I've got this C1-2858-3 error message on a specific game - in my case, DJMax Portable 1 (ISO), Korean version.

It's a quite old game, and I have no problems running newer versions of it (DJMax Portable 2, DJMax Clazziquai or DJMax Black Square) on Adrenaline-6 fix. All of them have large file sizes. Portable 1 has 1.41GB, Portable 2 has 1.65GB.

DJMax Portable 2 runs fine.

Also, I have a PSPGo with the same ISOs and all of them just run fine.
Is there any way to try "debugging" this problem?

**Comment by solitario001** [comment]
when playing mega man maverick hunter x (usa) psp after a while the game happens this error C1-2858-3 I already formatted my psvita is done a clean install plus the error continues this error happens after 10 to 20 minutes playing this game I have not yet tested other psp games I'm using sd2vita

**Comment by khromov** [comment]
@TheOfficialFloW Issue is still present on 6.61 Adrenaline-6.2. Can we please re-open?

**Comment by TheOfficialFloW** [comment]
Fixed in https://github.com/TheOfficialFloW/Adrenaline/commit/bcf05ef0e6b0ce09c70d6c20be3234f90434cfd7
