### ISSUE TITLE
No sound in pspemu

### ISSUE THREAD

**Issue by kamilb880** [TheOfficialFloW/Adrenaline#205]
Steps to reproduce:

- go to Adrenaline, sound is present (menu & on previewing PSP images)
- start PS1 game
- after some time press PS button and go back to Adrenaline's XMB

Sound is gone. Restarting Adrenaline fixes the problem, also putting Vita into standby mode and then waking it up fixes issue. Yet then battery in Adrenaline's XMB is showing like it is charging (Vita unplugged). Also standby mode fixes issue.

Issue spotted while launching & exiting MGS and Silent Hill
Appearance: 70-80% tries
Spotted on Adrenaline-6.

**Comment by HyeVltg3** [comment]
Just got the same issue today. But cannot fix after rebooting adrenaline. Even tried power off, no fix.
Playing any PS1 game. Sound works fine in PSP Games

**Comment by eclipznightz** [comment]
Having the same issue when running ff6 right now. Only appear when using the new 6.61 for 3.65 enso
