### ISSUE TITLE
Not an issue, but something great: Some PSP games run better than on a real PSP!

### ISSUE THREAD

**Issue by rsn8887** [TheOfficialFloW/Adrenaline#207]
I am not sure which games run better, but for sure Outrun 2 Coast to Coast definitely runs much smoother in Adrenaline than on a real PSP, both clocked to game: 333 MHz using the vsh menu.

On a real PSP, on the first track, there’s often slowdown where the game switches from 60 fps to 30 fps.

On Adrenaline, the game runs absolutely perfect 60 fps without slowdown. It is quite impressive, really. 

I wonder what other games run better in Adrenaline than on a real PSP? Maybe we can collect them here in the comments.

**Comment by TheOfficialFloW** [comment]
Cool :)
