### ISSUE TITLE
CWcheat not working for PS1 games

### ISSUE THREAD

**Issue by Ledah** [TheOfficialFloW/Adrenaline#21]
When holding select to activate CWcheat menu, music hangs and game seems to freeze, cheat menu doesn't appear. Pushing O return game to normal.

**Comment by shale1337** [comment]
To add to this TempAR 1.63 doesn't seem to work either. Another version 1.62-3 doesn't let to find anything and clicking any menu just makes it exit from TempAR.

**Comment by tamamushiiro** [comment]
cwcheatpops.prx works, but it doesn't display the menu. You have to mentally track where you are to enable the cheats properly

**Comment by ArgonUK** [comment]
This sounds important. It would be nice to enable PS1 16:9 widescreen hacks via cheat engine on PS Vita.

http://forums.pcsx2.net/Thread-PSOne-Widescreen-Patches?pid=477709#pid477709.

**Comment by TheOfficialFloW** [comment]
Added https://github.com/TheOfficialFloW/Adrenaline/commit/6fd9286653e297a64164e302764af02941cec79e
