### ISSUE TITLE
Error C1 2758-2

### ISSUE THREAD

**Issue by 94savz** [TheOfficialFloW/Adrenaline#210]
On 3.65 by mistake I opened Adrenaline Bubble Manager, then I opened Adrenaline and gave me error c1-2758-2.. if i installing again Adrenaline the error disappears..

**Comment by solitario001** [comment]
delete the PSPEMUCFW folder in ux0 / app and install again

**Comment by Korori03** [comment]
I am getting the same error and have completely uninstalled Adrenaline and made sure I delete ux0:app\PSPEMUCFG & ux0:pspemu\ via VitaShell.

**Comment by aqueleWillian** [comment]
I have unistall and delete the pspemu folder from ux0/ but the problem remains
