### ISSUE TITLE
stuck at 661.pbp installation

### ISSUE THREAD

**Issue by akbarsanjaya** [TheOfficialFloW/Adrenaline#211]
just installed adrenaline after updating to 3.65 enso.... for some reason it stuck at 661.pbp installation...

**Comment by RY0M43CH1Z3N** [comment]
what's happening when you start 661.pbp installation?

**Comment by solitario001** [comment]
delete the PSPEMUCFW folder in ux0/app and install again

**Comment by akbarsanjaya** [comment]
i was told to press x for 661.pbp installation... i pressed X  but it doesnt work

**Comment by TheOfficialFloW** [comment]
Manually download 6.61 eboot.pbp and put it at ux0:app/PSPEMUCFW/661.PBP

**Comment by dwedaz** [comment]
i got some problem try @TheOfficialFloW solution but still not working. please help.

**Comment by lKomus** [comment]
If you have VSHMenu or OclockVita installed, disable it entirely until you installed the firmware. For some reason, it conflicts with the installer and makes the installer not detect any button press.

**Comment by TheRadziu** [comment]
I can confirm its well known issue. If you have oclockvita enabled under *ALL this will happen. 

To bypass this add `*!PSPEMUCFW` before *ALL line. This will exclude *ALL plugins from being loaded when adrenaline starts.

**Comment by RealRaptoReX** [comment]
I have no all line for some reason, mine looks like this:

# For users plugins, you must refresh taiHEN from HENkaku Settings for
# changes to take place.
# For kernel plugins, you must reboot for changes to take place.
*KERNEL
ur0:tai/gamesd.skprx
ur0:tai/nonpdrm.skprx
ur0:tai/noavls.skprx
ur0:tai/renpdrm.skprx
ur0:tai/restore.suprx
ur0:tai/LOLIcon.skprx
# henkaku.skprx is hard-coded to load and is not listed here
*main
# main is a special titleid for SceShell
ur0:tai/henkaku.suprx
ur0:/tai/nolockscreen_v2.suprx
*NPXS10015
# this is for modifying the version string
ur0:tai/henkaku.suprx
*NPXS10016
# this is for modifying the version string in settings widget
ur0:tai/henkaku.suprx

can anyone help me? adrenaline crashes for me too with an black screen

**Comment by PablexxBoca** [comment]
Hi, I discovered the error that caused some application to work (in my case, the adrenaline 6.61.TheFlow in a comment above said to do this: "Manually download 6.61 eboot.pbp and put it at ux0: app / PSPEMUCFW / 661 .PBP "but in reality the file that they must move is the 661.bin, which in" ADRENALINE.VPK "is like" eboot.bin ", they simply change the name, and place it in a folder) in my case create the "PSPEMUCFW" and that's it. They install the vpk and it should work normally.
I AM A USER OF ARGENTINA. REGARDS
