### ISSUE TITLE
Wipeout Pulse DLC not working

### ISSUE THREAD

**Issue by dukzz** [TheOfficialFloW/Adrenaline#213]
I've been running 3.18 with TN-V until yesterday I switched to 3.60 with 6.61 Adrenaline.
It's great! But the only issue I'm having is that my DLC for Wipeout Pulse which I bought from PSN is not working anymore, when the game is loading savedata and DLC files it says:

Unable to load the download pack PSP/GAME/UCES00465/PACK1_U12. EDAT from Memory Stick Duo. This download pack will not be available during gameplay. (And it says it for every game pack)

It always worked when I used TN-V. As far as I can remember I downloaded the DLC's on my PSP, then copied the contents to GAME and LICENSE folders. I also tried downloading it fro the PSN's Download List in adrenaline but i get the error (80109D25) when downloading any content from PSN. My game regions do match, these ar the same files I have on my PSP and had on TN-V. Maybe it has something to do with PSN and system activation?

Any help or tips to get this to work is much appreciated!

**Comment by dude22072** [comment]
Looking at the game on the PS Store it seems this is one of the PSP games that can be downloaded to the vita directly. Have you tried downloading it from the Vita's PS Store and then running it from adrenaline?

**Comment by dukzz** [comment]
Thanks for looking out! My Vita is linked to my US PSN account, but the DLC is bought in UK store. I can see my DLCs in Dowload list when I log in Adrenaline/PSP UK store, but whenever I try to download something it shows the (80109D25) error after it attempts to activate the content. If I could download purchased content from PSPs store with Adrenaline this issue could be resolved I think.

**Comment by TheOfficialFloW** [comment]
Sony removed the ability to sign in with a PSID of a vita device. There is therefore no way you can download it legally with Adrenaline.

**Comment by dukzz** [comment]
Thank You for the reply and enormous work! I should've switched to Adrenaline earlier when it had the possibility to download content, since downloading legally is the only way to run that overpriced DLC.
I have another memory card linked to my UK account. Maybe I'll be able to get it to work if update to 3.65 HENkaku enso and transfer it from my PS3.

**Comment by dukzz** [comment]
In my case I found "patched" DLC files for this game.

**Comment by NeahNEET** [comment]
You mean decripted or version for SAVEDATA folder?

**Comment by dukzz** [comment]
Yes and no, DLC for this game goes to GAME folder. Took less than 2 mins to find em on google.

**Comment by NeahNEET** [comment]
Ok, thanks.
