### ISSUE TITLE
Update adrenaline vsh to match psp

### ISSUE THREAD

**Issue by animekai** [TheOfficialFloW/Adrenaline#214]
My issue is, i wanted to play umd movie iso on adrenaline,  but i noticed the vsh don't have all the options like psp 6.61 me has,  like umd iso mount, required to  mount movie iso.
There is a chance to update the vsh and have all the options from the psp, mainly to watch movies umd isos, please?

**Comment by TheOfficialFloW** [comment]
Not possible
