### ISSUE TITLE
Kernel module not running at startup

### ISSUE THREAD

**Issue by YoItsTrev** [TheOfficialFloW/Adrenaline#216]
Updated my Vita to 3.65 enso, got SD2Vita and NoNpDRM working. Installed Adrenaline 6.1. My config.txt looks like: 

# For kernel plugins, you must reboot for changes to take place.
*KERNEL
ur0:tai/nonpdrm.skprx
ux0:app/PSPEMUCFW/sce_module/adrenaline_kernel.skprx

Yet every time I restart the Vita, I have to run Adrenaline twice. Something is up.

**Comment by jeremyj563** [comment]
Where is your config.txt being loaded from? Keep in mind that if a config file is found at **ux0**:/tai/config.txt then **ur0**:/tai/config.txt will not load.

**Comment by YoItsTrev** [comment]
It is attempting to be loaded from ur0:tai. There is no ux0:tai. I deleted it, to make sure there was no conflicts, when I was trying to get NoNpDRM to load.

**Comment by IcySon55** [comment]
If this is on a PSTV, go into VitaShell, mount imc0:, and delete the tai/config.txt file you find there.

**Comment by Fish1717** [comment]
jeremyj563 yup that fixed the issue. Was editing the wrong config.txt file. 

Is there a reason to keep the ur0 config? Does it have a function?

**Comment by IcySon55** [comment]
I *only* use ur0:tai, this prevents the memory card or sd2vita from affecting your boot settings.

**Comment by irfanfadilah** [comment]
I'm on 3.60 and it's not loaded on startup, so I need to launch Adrenaline twice for the first time only.

I don't have config.txt anywhere except in ur0:tai.

Very minor bug, but it's there.

**Comment by IcySon55** [comment]
And your config.txt has the line to load the kernel plugin? (and the file is actually there?)
```ux0:app/PSPEMUCFW/sce_module/adrenaline_kernel.skprx```
