### ISSUE TITLE
Adrenaline freezes when I try to quit a psp game?

### ISSUE THREAD

**Issue by yodafire** [TheOfficialFloW/Adrenaline#219]
Posted this on Reddit, but no luck in resolving:
---------------------------------------------------

* mem: uma0 (sony card) fully works - currently running/storing psp/adrenaline games
* no plugins active just the gta mod one
* running on 3.60 hen enso
* psv100x system
* effecting GTA VCS/LCS/ChinTown

https://redd.it/89qf6f

https://redd.it/89us5p

as per title, yes it freezes, more specifically on the GTA series, I dont know why but when I try to quit the game the usual way PS button, quit game the crappy game keeps hanging, freezes Adrenaline completely then I have to reboot the vita (which goes into hard boot recovery screen). any suggestions or help or has anyone else had this issue. BTW i am using a normal iso 1.2-1.6GB file originals from emu paradise. all other games work fine just these one keep friking freezing when trying to quit the game properly.

EDIT: to those replying, try running these GTA games on your device and see if it freezes on you? use the ps button to "quit game" thats where the problem is it hangs, and forces your to hard restart

EDIT 2: steps when this happens:
* when I want to quit game, I tap the PS (home) button
* when the option comes up "do you want to quit game" I select yes
* the console then hangs (adrenaline hangs)
* I can use the PS (home) button to tap out of the freeze and back to live area
* but doing that means that adrenaline is STILL running in the back ground even though I have exited
* when I turn off vita from that point it hangs, as in the little bubble icon still animates when vita tries to shut down
* I have to hard reset this stage and it kicks me into safe mode, from which I just turn the vita off then on and Im back into enso
FYI its weird as this happens on only these GTA PSP games in adrenaline nothing else, I have like 72 PSP games and i can say that none of those have this affect apart from GTA

**Comment by TheOfficialFloW** [comment]
The issue seems to be the high memory layout. Disable in advanced configuration in the recovery menu.

**Comment by TheOfficialFloW** [comment]
v6.2 should fix this problem.
