### ISSUE TITLE
issues in PSX games NHL 99, FIFA 99, LT Sheep Rider, Heart of Darkness

### ISSUE THREAD

**Issue by fx3200** [TheOfficialFloW/Adrenaline#22]
hello i have issues in some game i tested

NHL 99 - after 1st period freeze game
FIFA 99 - after goal freeze (time run)
Looney Toons Sheep Rider - have slowdowns if you run and some other action
Heart of Darkness - menu glitch

thanks for your work

**Comment by TheOfficialFloW** [comment]
I can't enhance compatibility...
