### ISSUE TITLE
Kingdom Hearts Birth By Sleep Final Mix won't work on Adrenaline-6.1

### ISSUE THREAD

**Issue by Aw350meR060** [TheOfficialFloW/Adrenaline#223]
I'm using an english-patched iso, but the game gets stuck with a black screen on launch
I've heard that the game was working on the last version, so is there a way to enable it on -6.1?

Edit: found an EBOOT.BIN on reddit that helped me with my problem. Are there plans to fix this problem in Adrenaline itself though?

**Comment by TheOfficialFloW** [comment]
v6.2 should fix it again.
