### ISSUE TITLE
f.lux mode not working in 6.2

### ISSUE THREAD

**Issue by khromov** [TheOfficialFloW/Adrenaline#226]
f.lux is available in settings and when the options are toggled the screen does shift to the corrsponding hue, but as soon as exiting Adrenaline menu, screen goes back to normal, unfiltered mode.

**Comment by rsn8887** [comment]
Do you maybe have graphics filtering set to 'original'? 

F.lux and any other Adrenaline graphics options don't work if you set filtering to 'original.' There's even a reminder that appears in the menu on the bottom. This is intended. In original mode, all these options are disabled to improve speed.
