### ISSUE TITLE
Possible controller lag?

### ISSUE THREAD

**Issue by rsn8887** [TheOfficialFloW/Adrenaline#229]
I am not sure if this is true, but I seem to notice a very small input lag. Is Adrenaline doing something slow with the controller read-out, maybe using read() instead of peek()?

EDIT: I might just imagine things it is hard to tell.

**Comment by TheOfficialFloW** [comment]
Can you run a game without Adrenaline and see whether input is better there?

**Comment by meastes** [comment]
On a PS TV I seem to get more lag when using any display mode other than "Original". Maybe that's related?

**Comment by rsn8887** [comment]
It remains to be tested whether Adrenaline in 'original' mode has less lag than Adrenaline in 'bilinear' mode. I doubt it but I only tested 'original' mode.

It is a shame that even Sony's own PSN store PSOne Classics games have more input lag on Vita than on PSP, but at least that is not Adrenaline's fault.

**Comment by meastes** [comment]
The video filter lag I was seeing was only occurring when set to 1080i. When set to 720p, I didn't notice a difference between Original and Bilinear. So I guess that can be disregarded as an issue, though it would be nice to make note of that in the README.

**Comment by TheOfficialFloW** [comment]
Can I close this then?
