### ISSUE TITLE
Can not get Adrenaline v6.62 & v6.63 to work/open. C128... errors.

### ISSUE THREAD

**Issue by yodafire** [TheOfficialFloW/Adrenaline#231]
Just tried to update to version(s) 6.62 and 6.63 from 6.61FIX, but adrenaline fails to launch. I keep getting error C128 error upon launching adrenaline.

I have tried to install this from fresh, from the setup instructions (via zip/replace sce folder etc) and again no beans. Still will not launch adrenaline, and I keep getting the error message.

When I take a look at the PSPEMU... folder in uxo/app, it seems as though some files/folders are missing from the update.

files in foler are: the ones missing are in ( )

flash0 (MISSING)
flash1 (MISSING)
flash2 (MISSING)
flash3 (MISSING)
sce_module
sce_sys
eboot.bin
eboot.pbp
vitadb_info.yml

With those files missing adrenaline on v6.62/3 will not launch and keeps giving me error.
IF i put those files back in from a backup, then manually install v6.62/3 update sce_module files, again adrenaline fails to launch, and I keep getting the C1... errors.

I know adrenaline works fine on my Vita 100x 3.60 HE v11, as I reinstalled adrenaline version 6.61 FIX, which works but I had the previous GTA issue which freezes the vita when using the quit menu.

I know my vita works fine, I have reformatted countless times, my mem cards are fine, and they are Samsung genuine ones, not the cheap shit. I have no adrenaline plugins apart from camera patch lite enabled.

So as to this problem(s) i dont know WTF is wrong with this, its really annoying I can not even update now to the latest adrenaline.

Seems as though I'll be stuck on 6.61 FIX for a looooong time.

I have no idea how some other people are managing to update their versions to the latest on 3.60, as I for one can not be the only person to experience this update issue.

**Comment by TheOfficialFloW** [comment]
1. Install Adrenaline vpk
2. Reboot
3. Start Adrenaline

**Comment by yodafire** [comment]
> Install Adrenaline vpk
Reboot
Start Adrenaline

I tried that, it still gives me the error. I see the adrenaline black and grey splash background, but thats when the C1... error gets picked up. I can take a video of this if you want.

**Comment by TheOfficialFloW** [comment]
Why did you mention flash0-flash3 btw? These folders are supposed to be created by the installer, you don‘t need to create them. Be sure you start Adrenaline WITHOUT these folders.

**Comment by yodafire** [comment]
How can this be user error??? when clearly your vpk does not function properly.

1) I DID NOT create those folders, and I DID USE VITASHELL.

2) those folders were inside the 6.61 FIX, I looked inside that folder to check and backup prior to installing your updated versions.

(6.62/6.63 did NOT create any of those folders after installation finished, nor did it ask for the 661.PBP which the other adrenaline installations usually all ask for.)

3) after I installed the updated ones, and then got the errors, I looked inside the adrenaline folder and saw that only 4 of the files/folders were in there and those were:

sce_module
sce_sys
eboot.bin
eboot.pbp

The other folders were missing all missing, I even restarted the vita prior to launching adrenaline. they were still missing. 

you make no sense here at all, you stated: 

> Also install the vpk using VitaShell and DO NOT manually open it as zip

but yet your instructions mention:

> If you have already been using Adrenaline and want to quickly update, **simply open Adrenaline.vpk as zip file** and copy all modules from sce_module to ux0:app/PSPEMUCFW/sce_module.

I tried this way first, it failed, I started on a fresh install after by uninstalling the entire adrenaline app etc, again launched it using the vpk way in vitashell, AGAIN error C1..., 3rd time, remove adrenaline, reinstall adrenaline fix, went to VHBB, installed from there, restarted, after boot, launch adrenaline, ERROR C1, the process is getting ridiculous. your installation process only installs, but should it not ask for the PBP file?? even if its a fresh install, it wont ask for it. 

I have plugins disabled from vita so its not used by adrenaline simply by appending the following as the first line before the kernel: (I dont use ALL)

*!PSPEMUCFW

this allows me to not run any plugins whenever adrenaline is launched. (it completely bypasses the use of plugins from the vita to adrenaline.)

> This is for sure an user error

No its not, if your vpk does not ask me after a fresh installation for the PBP, in which it should, then how can this be user error, when I am clearly trying everything here.

I now have installed 6.61 over 7 times as fresh installs. (2 times for the 6.62, then when that failed I jumped over to fresh install of 6.63 SAME problems FFS) and yet you close this issue like its my fault. Like I said I CAN take a full video to show you how this is developing; as my proof that this keeps fucking up. just let me know, I can run this on fresh installs, right the way through to the way you suggest to upgrade it.

**Comment by TheOfficialFloW** [comment]
Can you try installing v6.1 fix again, then only copy adrenaline.suprx from v6.3 over?

**Comment by yodafire** [comment]
yeah give me 5 mins

**Comment by TheOfficialFloW** [comment]
If you have got adrenaline.skprx in config.txt try to remove this too.

**Comment by yodafire** [comment]
> If you have got adrenaline.skprx in config.txt try to remove this too.

so you want me to remove the line that should be in the config file: I have this from the time I installed fix:

ux0:app/PSPEMUCFW/sce_module/adrenaline_kernel.skprx

**Comment by TheOfficialFloW** [comment]
yeah

**Comment by yodafire** [comment]
okay done, I replaced the original v6.61 fix file (adrenaline_kernel.skprx) with the v6.63 file adrenaline_kernel.skprx, and removed the line fro mthe tai config file, I tried this, it seems to make me open adrenaline but on a double tap, I checked version its still 6.61

**Comment by TheOfficialFloW** [comment]
I said adrenaline_user.suprx....

**Comment by iamn0tdev** [comment]
Try to:

1. Remove this line from config
ux0:app/PSPEMUCFW/sce_module/adrenaline_kernel.skprx

2. Delete PSPEMUCFW folder from ux0:app
ux0:app/PSPEMUCFW/

3. Uninstall adrenaline from homescreen

4. Reboot 

5. Install Adrenaline 6.3 with Vitashell

6. Launch Adrenaline and let it download 6.61PBP

7. Relauch Adrenaline to install EMUCFW

**Comment by yodafire** [comment]
> Try to:

> Remove this line from config
> ux0:app/PSPEMUCFW/sce_module/adrenaline_kernel.skprx
> 
> Delete PSPEMUCFW folder from ux0:app
> ux0:app/PSPEMUCFW/
> 
> Uninstall adrenaline from homescreen
> 
> Reboot
> 
> Install Adrenaline 6.3 with Vitashell
> 
> Launch Adrenaline and let it download 6.61PBP
> 
> Relauch Adrenaline to install EMUCFW

Obviously you have not been reading enough into what has been going on with this issue, the above steps you mention have already been tried (**LOTS** of times).

**Comment by yodafire** [comment]
As an update, can not update past 6.1 Adrenaline, I even had a mobo change and I am now on 3.65 enso, told you this is not my vita, its a problem with your installer. Others may be able to install it fine, but I can't even following the instructions still errors out.

**Comment by umbrellaman11** [comment]
hey just wanted to chime in on this, im also on currently 6.1 adrenaline not the fix though, if i try to update i get the same problems as the user above. not sure whats causing this but can not properly update to the new version of adrenaline. (tried uninstalling/removing manually etc no dice bro)
