### ISSUE TITLE
cannot find -lvitashaders and -lAdrenalineKernel_stub

### ISSUE THREAD

**Issue by Yggdrasill-7C9** [TheOfficialFloW/Adrenaline#232]
I installed [libvita2d](https://github.com/frangarcj/libvita2d),
And I copied the [vita-shader-collection](https://github.com/frangarcj/vita-shader-collection/releases) library and includes to `usr/local/vitasdk/arm-vita-eabi`,
But the terminal still prompts me `cannot find -lvitashaders and -lAdrenalineKernel_stub`error.

What can I do to properly compile Adrenaline？
[error.log](https://github.com/TheOfficialFloW/Adrenaline/files/1923298/error.log)

**Comment by TheOfficialFloW** [comment]
https://github.com/frangarcj/libvita2d/tree/fbo

**Comment by Yggdrasill-7C9** [comment]
emmmmm.....But when I don't install these libraries, I still cannot compile properly.

**Comment by TheOfficialFloW** [comment]
Compile kernel stub first:
```
cd kernel
make build && cd build
cmake .. && make install
```

**Comment by Yggdrasill-7C9** [comment]
Thank you...It seems that my installation failed....I still can't find lvitashaders....

**Comment by TheOfficialFloW** [comment]
Not related to adrenaline then if you fail to install the library
