### ISSUE TITLE
Save states disappear after updating from 6.1 to 6.3

### ISSUE THREAD

**Issue by BlackRabbit22** [TheOfficialFloW/Adrenaline#233]
The save states somehow disappeared after updating from 6.1 to 6.3. 
If I go back to version 6.1 the save states show up but if i re-update again, the save states are disappear.

You can reproduce the bug by creating a save state for any game on 6.1, and then updating to 6.3.

**Comment by TheOfficialFloW** [comment]
That's intended that savestates are not compatible between different version, since these savestates are full ram dumps. There may therefore be conflicts if you load a ram dump from a previous version, but your current is a much different one.
