### ISSUE TITLE
adding autoupdate?

### ISSUE THREAD

**Issue by bigretromike** [TheOfficialFloW/Adrenaline#24]
It would be awesome to add update via Update system inside adrenaline (as old cfw did it) but if that's not the case it would be awesome to be able to make updates automatic. 

If its out the scope, please close this issue.

**Comment by TheOfficialFloW** [comment]
Added https://github.com/TheOfficialFloW/Adrenaline/commit/5054b97067a41f0be8a2d6dd063add21e795bcbe
