### ISSUE TITLE
Tekken 6 overclock support

### ISSUE THREAD

**Issue by Catarax** [TheOfficialFloW/Adrenaline#240]
On 6.61 PRO-C for PSP Go, Tekken 6 can run with CPU CLOCK Game at 333mhz/Inferno.
The custom firmware fakes the cpu clock from what I read, to avoid the blackscreen.

It would be great to have that on Adrenaline / forced at 222mhz for this title when played as iso/cso.
Thanks!

**Comment by cvskid** [comment]
Yeah i noticed that too with the game not working when overclocked.

**Comment by Catarax** [comment]
I recommend to purchase the version on the Playstation Store, it will run without issues on the vita bubble menu or in adrenaline.

**Comment by TheOfficialFloW** [comment]
Added in https://github.com/TheOfficialFloW/Adrenaline/commit/06dcde1aaad07199613b652357f002e8a89bd406.
