### ISSUE TITLE
Anyway to run DJmax portable 1 on Adrenaline?

### ISSUE THREAD

**Issue by murdererdu** [TheOfficialFloW/Adrenaline#243]
I ran the game and got C1- error. I have updated my vita to 3.65 ENSO and ARK doesn't compatible with 3.65. How can I run the game on 3.65 ENSO?

**Comment by TheOfficialFloW** [comment]
Fixed in https://github.com/TheOfficialFloW/Adrenaline/commit/bcf05ef0e6b0ce09c70d6c20be3234f90434cfd7
