### ISSUE TITLE
SD2Vita Storage not correct when using 256GB Card

### ISSUE THREAD

**Issue by Smoker1** [TheOfficialFloW/Adrenaline#245]
I Upgraded to a 256GB Card from a 128GB Card. I still had 50+GB left on it prior to using it in Adrenaline, but for some reason, it said I had 0KB, it would not let me Save any Games, but when I Deleted a Game, I got Storage Available.
Odd thing is, I have a different Issue with VitaShell not Showing the Storage amount correctly of the Card, but I am able to use it.

**Comment by Smoker1** [comment]
I have 95.4GB left of 238GB, but VitaShell and Adrenaline (had to Delete a Game from Adrenaline): 237.61GB / 238.29GB or 0.68MB (693MB under Adrenaline)

**Comment by Smoker1** [comment]
I think I found the Issue with the Cards. It seems, in the Formatting process for the SD2Vita MicroSD Card, it has the Problem. A 128GB Card has no Problems. But 200GB+ Cards have the Issue. I Tested a 200GB SanDisk (Orange Font on Black) Card, and it had the same Issue. As you can see, my PSVSD does not have a Problem, since it is just simply Formatted with no .img File needed for it.
![20180617_090407-1](https://user-images.githubusercontent.com/8584462/41511099-57cf0322-7225-11e8-8969-af7b0dae7e5e.jpg)

**Comment by mathieulh** [comment]
You need to format your SD card with a cluster size of 64kB to fix this issue. 
This is also not an adrenaline issue to begin with.

**Comment by Smoker1** [comment]
Actually it is doing the same within Adrenaline. I should have now, around 80GB in it, but it only shows around 8GB now.
