### ISSUE TITLE
Support for the newly added xmc0: in VitaShell for Adrenaline

### ISSUE THREAD

**Issue by Zeitwaechter** [TheOfficialFloW/Adrenaline#248]
Hey there!

I would like to ask if there is any possibility to add `xmc0:` to the possible data endpoints in Adrenaline to the settings as it is now a thing in your latest update in VitaShell.

A short note on this would be nice.

Tank you very much in advance :)

Kind regards!

**Comment by akiba01** [comment]
Any update on this?

**Comment by Zeitwaechter** [comment]
Not that I know of, besides the referenced duplicate - but neat workaround anyways.

Still hoping for an official change though :)

Thanks in advance, again :+1:

**Comment by TheOfficialFloW** [comment]
Will be available next update: https://github.com/TheOfficialFloW/Adrenaline/commit/3352186d332891770343865149a05f6d27a717b0
