### ISSUE TITLE
Error: 80109D25 - Won't download PSP Games from PSN Download List in Adrenaline

### ISSUE THREAD

**Issue by ABOhiccups** [TheOfficialFloW/Adrenaline#252]
I got Adrenaline installed on PSTV. I think this is the best way to play PSP Games. I try to download any PSP Game off PSN Download List. I get a error message won't download a PSP Game.

Is there other way without illegal piracy download?

**Comment by TheOfficialFloW** [comment]
Not fixable - blame Sony.
