### ISSUE TITLE
Corrupts everything. (MASSIVE ISSUE)

### ISSUE THREAD

**Issue by lunalik2** [TheOfficialFloW/Adrenaline#255]
Upon installing adrenaline 6.4, an individual, as well as myself, have suffered from our memory cards getting bricked. This is a massive issue, and so this doesn't happen to anyone else, please take down 6.4 from the page. This has costed some a lot. https://gbatemp.net/threads/adrenaline-corrupted-my-card.509921/#post-8111522

**Comment by TheOfficialFloW** [comment]
How about no? 6.4 changes are little and no way it was the reason, it does merely touch the filesystem.

**Comment by lunalik2** [comment]
it could be 6.3 then
