### ISSUE TITLE
Savedata and USB mode not working when using SD2VITA mounted on imc0

### ISSUE THREAD

**Issue by Linkandzelda** [TheOfficialFloW/Adrenaline#258]
This is a strange one. To combat an issue with SD2VITA when mounting to uma0 using storagemgr.skprx I chose to mount my SD at imc0 and redirect the actual imc0 to uma0. This allowed me to remove and reinsert the SD whenever I wanted to play a vita game card. (with uma0 this remount does not happen hence the workaround to imc0).

The behaviour that happens when using the above is quite strange. ISOs are detected and can be launched, but USB mounts the actual imc0, and save data cannot be found. I assume that Adrenaline is coded to look directly at the imc0 when choosing to use imc0 for the PSP memory card, despite it actually being mounted as my SD?

**Comment by TheOfficialFloW** [comment]
Fixed https://github.com/TheOfficialFloW/Adrenaline/commit/3352186d332891770343865149a05f6d27a717b0
