### ISSUE TITLE
Screenshots bugs on PS1 titles

### ISSUE THREAD

**Issue by KDOXG** [TheOfficialFloW/Adrenaline#26]
When you press PS + Start, the Vita default command to make screenshots, during PS1 titles, the screenshots stays all "damaged".
Example: ![2017-04-16-205807](https://cloud.githubusercontent.com/assets/26307688/25103000/3275c658-2391-11e7-9682-bd00937ac7f3.jpg)

I just want to know if it's a issue that can be resolved, or we will really need to use the official print screen feature from the PSX emulator part.

**Comment by deadair3210** [comment]
Probably not going to be able to use the Vita Screenshot feature, as that is the same thing you would see if you looked at vram in a emulator.

**Comment by TheOfficialFloW** [comment]
Will be fixed in the next update.

**Comment by CelesteBlue-dev** [comment]
@TheOfficialFloW Maybe you could use SceCompatPs1SaveScreenShot.

**Comment by deadair3210** [comment]
Shows how much I know, lol.

**Comment by pthfdr-42** [comment]
Still not fixed in the latest version, also after saving the screenshot, the Vita freezes.
