### ISSUE TITLE
Error PSP games on Adrealine : The game could not be started (80010087)

### ISSUE THREAD

**Issue by LinkTH99** [TheOfficialFloW/Adrenaline#261]
I used Adrealine 6.61 v6.1 to play Resistance and MOH . 
After 2 weeks , when i open Adrealine , those games auto delete ( but not save file ).
I delete Adrealine v6.1 and install 6.3 version. But when i started PSP games , the screen always appear this error : The game could not be started (80010087).
I tried put ISO file into pspemu / ISO but Adrealine can't recognize those file. 
Can anyone know how to solve those problems ?

**Comment by Marioh2451** [comment]
Hi the solucions that i have found didn't work one of them was sepkugins and other one was enabling EVERYTHING in recovery menú Mode :/

**Comment by LinkTH99** [comment]
Marioh2451 can you explain , i don't know about sepkugins

**Comment by Marioh2451** [comment]
Seplugins* theflow said in the release of V6 there was a file from somewhere to flash2 of adrenaline. It doesn't work.
I have found the solution and it's a problem of 661.pbp I Will pm u for a link ok?

**Comment by TheOfficialFloW** [comment]
You lost your act.dat.

**Comment by LinkTH99** [comment]
TheOfficialFloW thank ,  i install adrenaline v6.4 and now it recognize ISO file. 
My problem is i can't play PSP or PSX game downloaded from PKGJ .
