### ISSUE TITLE
80010005 When booting certain game

### ISSUE THREAD

**Issue by 9BitStrider** [TheOfficialFloW/Adrenaline#262]
FW: 3.68 w/ h-encore & 6.61 Adrenaline 6.4
PCH-1101 model w/ PSVSD (128 GB ux0) and Memory Card (64 GB uma0)
Game: King's Field (J) English Patched

I get the above error when attempting to boot this game in Adrenaline. I've used pre-patched/converted version and converted the ISO myself and I get the same result (PSN version available through pkgj works fine. I just can't read Japanese). It's a minor issue (I doubt there are many KF fans out there) but I would like this game to be playable if at all possible. Thank you for your hard work.

**Comment by 9BitStrider** [comment]
Also getting error 80010148 when trying a converted ISO using POPStation.

**Comment by 9BitStrider** [comment]
Game works in ePSXe for both PC and Android and also runs on actual hardware.

**Comment by 9BitStrider** [comment]
Newest update to Adrenaline fixed the issue. Thank you for the hard work.

**Comment by ryan44431** [comment]
i have this problem cant fix it i updated and everything my original buyed games world in the adrelaline but the downloaded ones / converted to eboot wont start i get this meesage 80010005  have tried resident evil 2 resident evil 3 tomb raider 3 they all get same glitch any help ? :(

**Comment by DyruGun** [comment]
mine still not work

problem is save data, once i remove save data the game can be play again

but i want to continue my save data
play suikoden psn eboot euro

**Comment by ryan44431** [comment]
i cant run a single game get that error allways :(

**Comment by DyruGun** [comment]
Ryan

already play like me or  even can't play for first time?

**Comment by ryan44431** [comment]
not even once tried resident evil 3 tomb raider abes odyssey all say the ame the game could not be started 80010005
