### ISSUE TITLE
Internal error with sd2vita as USB device

### ISSUE THREAD

**Issue by nameless1** [TheOfficialFloW/Adrenaline#263]
Every time I try to use the sd2vita with USB on the new 6.61 6-5 release It errors out with: An internal error has occurred. (80244112)

Using Celeste Blue Storage manager 2.1 if it matters.

**Comment by TheOfficialFloW** [comment]
Damn, I only copied the code from VitaShell without testing it. Seems like it cannot work due to few permissions.

**Comment by nameless1** [comment]
Drat, Hope it can be fixed, not a huge deal because you can still transfer from vitashell itself but it would be nice to use USB mode in adrenaline.

**Comment by K4thos** [comment]
some more info:

*Adrenaline v6.7 config*
Memory Stick Location: uma0:pspemu
USB device: sd2vita

*USB connection result*
An internal error has occured. (80244112)

**Comment by JacobMrox** [comment]
I'm still having the same issue as well, the same as the one guy above me, it doesn't matter what the memory stick location is, just as long as the USB device is sd2vita this error still shows up.... any clue?
