### ISSUE TITLE
Multiple DJ max games crashing with 6.61 Adrenaline-6.5

### ISSUE THREAD

**Issue by cvskid** [TheOfficialFloW/Adrenaline#264]
I have multiple dj max games that i play through adrenaline and when upgrading from adrenaline version 6.4 to 6.5, While dj max portable 1 works again the new update causes the games dj max portable clazziquai edition and dj max portable hot tunes to crash upon booting the games up to play them.

When booting the games there is a black screen and when you press the playstation button to try to exit the game back to the psp xmb, nothing happens. You have to press and hold the playstation button to go to settings and "exit pspemu application". The games work fine on adrenaline 6.4

my adrenaline vsh menu settings are all default

CPU CLOCK XMB  Default
CPU CLOCK GAME Default
UMD ISO MODE Inferno

**Comment by TheOfficialFloW** [comment]
can you try changing the driver?

**Comment by cvskid** [comment]
Changing the driver to M33 Driver results in a crash with a black screen and changing the driver to Sony NP9660 also results in a crash with a black screen.

**Comment by TheOfficialFloW** [comment]
can you go back to v6.4 and test again?

**Comment by cvskid** [comment]
Went back to adrenaline 6.4 like you said and tried the games out. They load and work using the Inferno Driver, the M33 Driver, and the Sony NP9660 Driver.

**Comment by TheOfficialFloW** [comment]
Fixed in https://github.com/TheOfficialFloW/Adrenaline/commit/06dcde1aaad07199613b652357f002e8a89bd406 again.
