### ISSUE TITLE
Manhunt 2 not working

### ISSUE THREAD

**Issue by gallop420** [TheOfficialFloW/Adrenaline#27]
There's no crash and the game starts but it gets stuck when loading the first level. I'm using an ISO if that matters and I haven't had this issue with any other Rockstar games.

**Comment by apizzamra** [comment]
![1491843472275](https://cloud.githubusercontent.com/assets/27785013/25200218/bfa601d6-2577-11e7-8b1b-3d19dfb7655e.jpg)
works fine for me

**Comment by gallop420** [comment]
Do you have everything on stock settings?

**Comment by apizzamra** [comment]
yes, everything is on default except the cwcheat

**Comment by bosshunter** [comment]
The game runs fine for me. Tested with both EU and US versions.

**Comment by gallop420** [comment]
It's not running in PSTV  using Adrenaline 4. Everything is set to stock and I'm not using any plugins or filters.

**Comment by gallop420** [comment]
It starts to load the first level then stops loading. It doesn't freeze but just won't load the level no matter how long I wait.

**Comment by bosshunter** [comment]
Tested now on the PSTV and it runs fine. Maybe you have a bad iso?
