### ISSUE TITLE
Multiplayer Split Screen with Psvita + DS4

### ISSUE THREAD

**Issue by reidsneo** [TheOfficialFloW/Adrenaline#277]
Hello TheFlow!
It has been great inovation since last emulator on psp for playing psx game,
me with my wife want to nostalgia which we want to play "Chocobo Racing" a PSX Game with multiplayer support, since now we allowed to use option "Use DS3/DS4 controller",
Can you please make a feature to allow us play with psvita as controller 1 and DS4 as controller 2
It would be great if possible.

Thanks!

Best Regards
Reids

**Comment by TheOfficialFloW** [comment]
That's in my todo list :)

**Comment by reidsneo** [comment]
Wohooooo....!!
I can't wait for it!
Again thanks!

Best Regards,
Reids

**Comment by TheOfficialFloW** [comment]
Added https://github.com/TheOfficialFloW/Adrenaline/commit/8ca7da16eec593bc8bd2f3a83298beeb6facd206.
