### ISSUE TITLE
Adrenalin6.61 rebooting Vita on load? 

### ISSUE THREAD

**Issue by RSG3** [TheOfficialFloW/Adrenaline#279]
So i recently did the h-encore soft mod and when i put Adrenaline on the machine either via apk or through the VHBB and boot Adrenalin the screen goas black then the PS logo pops up the Vita boot warnings then the OS and a message saying the machine was shut down improperly. Ive spent a few days trying to google and look around for a solution but i haven't seen anyone mention something like this so i'm now asking 

Any thoughts? Thanks for your time.

**Comment by plxjammerplx** [comment]
Do a clean install of henkaku and adrenaline.

**Comment by RSG3** [comment]
I uninstalled Tai-Henkaku and Adrenaline and clean reinstalled both and it still reboots the machine.
