### ISSUE TITLE
MGS - Psycho Mantis, switching gamepad slot

### ISSUE THREAD

**Issue by Rameron** [TheOfficialFloW/Adrenaline#280]
Hello.
In Metal Gear Solid for defeat of the boss named Psycho Mantis, you need to reconnect your PS1 gamepad to the second slot of console. But in Adrenaline even after changing your active gamepad to second, it's not working properly. Is it hard to add the full support of the second gamepad?

Last theme was simple closed without any comment by Flow.

Thanks.

**Comment by NeonLightning** [comment]
https://github.com/TheOfficialFloW/Adrenaline/issues/277

**Comment by dude22072** [comment]
This is a completely separate issue that the one @NeonLightning linked.

**Comment by Grazgamer** [comment]
It’s not a MGS issue, more that the controller switch does not work in adrenaline.

**Comment by TheOfficialFloW** [comment]
See if it works with v6.7.

**Comment by Rameron** [comment]
Yeah, it's really work in 6.7, thanks!
