### ISSUE TITLE
"An error has occured. (C1-2758-2)" On launch

### ISSUE THREAD

**Issue by JoeMcsk** [TheOfficialFloW/Adrenaline#281]
When i launch the adrenaline bubble im greeted with this error everytime 
Ive uninstalled several times with the issue still taking place. Any help!?

**Comment by plxjammerplx** [comment]
Changed the eboot file(104kb) in the pspemucfw back to eboot.pbp. Manually download the 661.pbp(named eboot.pbp) file, rename it to 661.pbp, and place that file in ux0:app/pspemucfw. Reinstall Adrenaline.vpk then run Adrenaline once again.

Make sure you have Henkaku running.

**Comment by harukis86** [comment]
um where i could manually download this 661.pbp ?
could you be more specific ? thank you

**Comment by harukis86** [comment]
i already download it manually and change the eboot to 661 as you said and re install the adrenaline
it's still the same i got the same error
