### ISSUE TITLE
No se descarga el 661.PBP 

### ISSUE THREAD

**Issue by ADRIAN10101** [TheOfficialFloW/Adrenaline#282]
Se me trabó el wifi y no puedo más descargar ayuda

**Comment by Monumilnides** [comment]
Borra la aplicación, luego reconstruye la base de datos, vuelve a instalar el vpk de adrenaline.

**Comment by Monumilnides** [comment]
Borra la aplicación, luego reconstruye la base de datos, vuelve a instalar el vpk de adrenaline.
