### ISSUE TITLE
adrenaline 6.7 ds4 l2/r2 issue

### ISSUE THREAD

**Issue by hoholee12** [TheOfficialFloW/Adrenaline#287]
it seems new update has made l2/r2 buttons not working again.
it was working fine on 6.6
im using ds4vita and ds4
ive tried 'use ds3/ds4 controller'
i think it could be a simple fix... please address this issue thanks!

**Comment by TheOfficialFloW** [comment]
Use https://github.com/TheOfficialFloW/MiniVitaTV/releases/tag/v0.2

**Comment by hoholee12** [comment]
minivitatv is still too buggy for me so i guess im staying on 6.6 for now.... thanks

**Comment by ephb** [comment]
Hi,
it seems like this bug is also affecting the l2/r2 emulation with the analog sticks and touchpads
