### ISSUE TITLE
C1.2858-3 ERROR when i load up a certain PSP game within Adrenaline.

### ISSUE THREAD

**Issue by AbdulAli17** [TheOfficialFloW/Adrenaline#294]
I have been trying to transfer a copy of WWE Smackdown VS RAW 2011 onto my vita. Everything goes well until i try to boot upthe screen, the display goes black and the error pops up. After which i can't access Adrenaline at all due to the same error. However this is temporarily fixed when i reboot the device and reinstall h-encore. But when i try to start the same game again the error pops up again and the same thing happens again. HELP!!!

**Comment by TheOfficialFloW** [comment]
if I see HELP!!! or PLEASE!!! I will immediately close.

**Comment by AbdulAli17** [comment]
Why may I ask?
