### ISSUE TITLE
Adrenaline Menu is not displayed when enable or disable wifi

### ISSUE THREAD

**Issue by iamn0tdev** [TheOfficialFloW/Adrenaline#3]
How to reproduce it:
1. Hold PS button
2. Enable or disable wifi
3. Settings (top right corner)

I've tested enabling/disabling airplane mode and bluetooth but the issue is only reproduced with the above

Base game: Echochrome and Ape Quest

**Comment by GrayJack** [comment]
I can reproduce that
Base game: Bubble created with ePSP Bubble Installer

**Comment by TheOfficialFloW** [comment]
Fixed https://github.com/TheOfficialFloW/Adrenaline/commit/f99d5a5189b63a9d8b55a0fac3eb6186b3a97c87
