### ISSUE TITLE
Adrenaline crashes when M4A files are played

### ISSUE THREAD

**Issue by Dartegnian** [TheOfficialFloW/Adrenaline#306]
MP3 files play just fine. Playing M4A files crashes Adrenaline and creates a sort of "deadlock" situation in which the user is unable to reboot or launch any new application. This forces you to fully restart your Vita by holding the power button until it reboots.

![Example 1](https://i.imgur.com/uVZ71b1.png)
![Example 2](https://i.imgur.com/HSGDaNe.png)

**Comment by RuggeDX** [comment]
I don't think the PSP firmware supports M4A.

**Comment by TheOfficialFloW** [comment]
yeah due to missing media engine.

**Comment by Dartegnian** [comment]
@RuggeDX The PSP **does** support M4A. You can try it for yourself, if you still have a working one. I tried it myself and M4A files play fine.

Anyway, thanks, @TheOfficialFloW for clearing things up and responding to this. Appreciate the work you put into Adrenaline!

**Comment by TheOfficialFloW** [comment]
Can you send me the file anyways btw?

**Comment by Dartegnian** [comment]
Oh hey, @TheOfficialFloW. Sorry for the late response. [Here's a link to one of the files that I played.](https://drive.google.com/file/d/1ENhuVWS6nhos5XLq6-gRv2GumIscRliZ/view?usp=sharing) I just want to point out that any fully-updated PSP model can play this file just fine without errors, in case someone asks. Tried it on my PSP Slim.
