### ISSUE TITLE
Download of firmware 6.61 after adding adrenaline_kernel.skprx

### ISSUE THREAD

**Issue by CidVonHighwind** [TheOfficialFloW/Adrenaline#310]
Currently Adrenaline won't download the firmware if adrenaline_kernel.skprx has already been added (and the device was rebooted). This can be a problem if someone is updating by installing the .apk or not downloading the firmware before rebooting the device with adreanaline_kernel.skprx added.

**Comment by TheOfficialFloW** [comment]
this is intended.
