### ISSUE TITLE
Small issue when press on PS vita home button while in game to save state...

### ISSUE THREAD

**Issue by alpakeno** [TheOfficialFloW/Adrenaline#312]
To replicate the issue:
1- Press PS vita home button then press it again to close the gray psp exit game screen.
2- Press and hold the PS vita home to open adrenaline menu, the gray psp exit game screen will appears in the background and this will be an issue if I try to use savestate, because it will not capture the game background picture.

**Comment by RuggeDX** [comment]
Leave it on the gray screen and hold the PS button again so you can see the game. It's not that hard.
