### ISSUE TITLE
C1-2858-3 error with 6.61 Adrenaline-6.7

### ISSUE THREAD

**Issue by AkitoCL** [TheOfficialFloW/Adrenaline#315]
I tried uninstalling Adrenaline on a second hand vita because custom bubbles weren't working correctly and after reinstalling it I can't get it to work.

I'm using a Vita 2000 with SD2Vita. Tai folder with plugins and config.txt is just in ur0.

Edit: Solved... I think. I deleted the seplugin folder from pspemu, reinstalled Adrenaline and now everything is fine.

**Comment by nifcapili** [comment]
>           I tried uninstalling Adrenaline on a second hand vita because custom bubbles weren't working correctly and after reinstalling it I can't get it to work.
> I'm using a Vita 2000 with SD2Vita. Tai folder with plugins and config.txt is just in ur0.
> Edit: Solved... I think. I deleted the seplugin folder from pspemu, reinstalled Adrenaline and now everything is fine.

I can confirm than seplugins folder might be the issue. I just renamed it to something else. voila it now works!
@TheOfficialFloW

**Comment by nifcapili** [comment]
Update: it appears that CXMB 6.61 is not compatible with adrenaline 6.7. I just removed it from vsh.txt and now it is working fine with seplugins
