### ISSUE TITLE
Adrenaline freezes while having LOLIcon Plugin

### ISSUE THREAD

**Issue by ElBionox** [TheOfficialFloW/Adrenaline#317]
adrenaline keeps freezing while having lolicon plugin, might have to look into that

**Comment by dude22072** [comment]
No overclocking plugins work with adrenaline. Just disable the plugin for adrenaline.

**Comment by Babbosh** [comment]
Dude how do you disable the plugin for a specific app such as Adrenaline? I have the same problem after I installed Lolicon.
