### ISSUE TITLE
PS button

### ISSUE THREAD

**Issue by AmiDonk** [TheOfficialFloW/Adrenaline#32]
Hey. Love your work.. You are the man.
When i press PS button 2 times, a window says: Cant find software?

Q: use of real images like bin cue with cd audio instead of eboot images. Can it be done in future.. It should be very neat...

Best regards.

**Comment by CelesteBlue-dev** [comment]
Are you using latest Adrenaline (v3.1) ?
You can update easily using Adrenaline Easy Installer v1.09 by Freakler.
