### ISSUE TITLE
PSP games error at launch 80010002 

### ISSUE THREAD

**Issue by j0wnz** [TheOfficialFloW/Adrenaline#320]
Hi!

When I try to initialize a game downloaded by pkgi, I 've got this error "80010002 unable to start the application " After that, the system becomes unstable and I must reset my ps vita by pushing on/off button several seconds...

Is there any solution? Thank you!

**Comment by Neito-kun** [comment]
Did you uncompress/convert the game to ISO format correctly after downloading it? Or are you trying to run it directly from pkgi file format? Also, are you downloading the games directly in your Vita console? Or are you downloading them using a PC and copying the files later, in your Vita? Try using NPS Browser...
