### ISSUE TITLE
[REQUEST]pocketstation app and adrenaline,possible?

### ISSUE THREAD

**Issue by crazy2k4** [TheOfficialFloW/Adrenaline#321]
hi,theflow,first thanks for you work,is awesome
i' have a question
is posible add pockestation suport in adrenaline?

**Comment by nanashi89** [comment]
Sorry to hijack, but while the question is still open, is there any chance of adding support for TurboGrafx-16 on PSP support as well?

**Comment by TheOfficialFloW** [comment]
yeah but I'm not interested in adding.
