### ISSUE TITLE
Error: pspPSARInit failed (0xFFFFFFFF)

### ISSUE THREAD

**Issue by SamuelRuGo** [TheOfficialFloW/Adrenaline#322]
Hi everyone,

I'm new modifying PSVita. I want to install Adrenaline but i get the following error:

**pspPSARInit failed (0xFFFFFFFF)**

I just formatted the console and done a clean installation. Can someone help me solve this problem?

THANK YOU VERY MUCH

**Comment by Asentum** [comment]
I'm having the same issue. Have you found a solution yet?
