### ISSUE TITLE
No Custom Screen Size for PSOne on PS TV.

### ISSUE THREAD

**Issue by nanashi89** [TheOfficialFloW/Adrenaline#327]
I tried to make my PSOne games on Adrenaline Fullscreen on PS TV, but custom screen settings are absent.

Why? Weren't they included in the Vita version?

**Comment by TheOfficialFloW** [comment]
ask Sony why. You can have fullscreen with adrenaline settings though if you would explore it first before you file in an issue...

**Comment by rsn8887** [comment]
I recommend to use the Adrenaline menu (not Sony menu) to set graphics: bilinear, set smooth graphics: on, and use the following scaling options.

VitaTV 4:3:
Screen Scale X (PS1) = 1.185
Screen Scale Y (PS1) = 1.000

VitaTV stretch-to-widescreen:
Screen Scale X (PS1) = 1.500
Screen Scale Y (PS1) = 1.000

Vita 4:3:
Screen Scale X (PS1) = 1.135
Screen Scale Y (PS1) = 1.135

Vita stretch-to-widescreen:
Screen Scale X (PS1) = 1.5
Screen Scale Y (PS1) = 1.135
