### ISSUE TITLE
PSP/PSone games not showing up (uma0 and ux0)

### ISSUE THREAD

**Issue by nirvana-phoenix** [TheOfficialFloW/Adrenaline#334]
For some reason, only a handful of my PSP ISOs and PSone EBOOTs are showing up in Adrenaline on my PSTV.

They aren't showing up when the memory stick is set to ux0 or uma0, even though the file paths are correct (uma0/ux0:PSPEMU:ISO and PSPEMU:GAME:SCUSxxxxx, respectively).

The first batch of ISOs and EBOOT I put on the uma0 work fine, but ones I've transferred since don't appear at all, although VitaShell can find them and they take up memory. I tried deleting one of the ISOs from the first batch and putting it back on, and now it's gone. Moving a game from the um0 to ux0 didn't make it appear either.

I have a feeling it might be due to tai config files or adrenaline-kernel.skprx files being in the wrong place, but honestly, I'm stumped.

**Comment by TheOfficialFloW** [comment]
Must be ux0:pspemu/PSP/GAME

**Comment by nirvana-phoenix** [comment]
What about ux0:pspemu/PSP/GAME?

**Comment by TheOfficialFloW** [comment]
You wrote a pathname that was incorrect (missing /PSP/), so I corrected you and now you ask what about it?

**Comment by nirvana-phoenix** [comment]
I confused myself writing out my OP, sorry. The EBOOTs are in pspemu/PSP/GAME and then their own folders. Should they just be in the GAME folder?

**Comment by rsn8887** [comment]
Use FTP to transfer files.
