### ISSUE TITLE
Sharp-Bilinear-Simple shader (without scanlines)?

### ISSUE THREAD

**Issue by rsn8887** [TheOfficialFloW/Adrenaline#336]
EDIT: Pull Request made https://github.com/TheOfficialFloW/Adrenaline/pull/338 . With that PR, and selecting the new shader “sharp bilinear without scanlines” under graphics filtering, it looks and works perfect. Sometimes I still get slowdown when just loading up a PS1 game, but entering the Adrenaline menu and exiting the menu fixes that. I opened a different issue for that separate problem, which is independent of the shader selected or the issue discussed here.

Sharp-Bilinear-Simple gives the sharpest pixels with minimum blur possible for the given Screen Scale X and Y settings, without adding any scanlines or any other effect, and without allowing "pixelwobble". For it to work, smooth graphics have to be on. For more information, see here: 
https://github.com/rsn8887/Sharp-Bilinear-Shaders

The following observation is what led to mu Pull Request:

I did some more tests on my Vita TV today with the game Lomax on PS1 and found the  following:
- Graphics Filtering: Bilinear causes screen tearing mostly in the lower left corner of the screen during scrolling
- Graphics Filtering: Sharp-bilinear, Advanced AA, or LCD3x do not cause screen tearing, the scrolling is perfect.

However, while the three shaders Sharp-bilinear, Advanced AA, and LCD3x work and might look ok for some users' taste, especially with PSP content, I think look terrible with PS1 games. The filter Sharp-bilinear causes ugly vertical scanlines/moire patterns to appear on the TV, the filter Advanced AA causes excessive blurring which makes the PS1 image look less like pixel graphics and more like a painting (some people might like it, but I hate the blurry look), and LCD3x causes an ugly square black raster to appear on top of the image that is also not perfectly aligned with the PS1 pixels.

So, currently, there’s no filter that gives smooth scrolling without tearing for PS1 games that doesn’t also mess up the image somehow.

Therefore my suggestion is to add the sharp-bilinear-simple shader as an option. It does the same as sharp bilinear but it doesn’t add any scanlines or any other pattern to the image.

Edit: Since sharp-bilinear-simple is already part of vita2d_fbo and Vita-shader-Collection, I just made a quick PR that allows users to enable it. It works great and gives perfectly smooth scrolling on VitaTV with Lomax on PS1, in the same situations where “graphics filtering: bilinear” causes screen tearing.

**Comment by rsn8887** [comment]
Thanks for merging!

**Comment by CricoVita** [comment]
hello I have a problem with adrenaline to emulate this PS1 game is the "Bust a Groove" since in my psvita is not synchronized neither the graphics nor the audio, please if you check the error thanks in advance
