### ISSUE TITLE
Slowdown in PS1 sometimes but entering Adrenaline menu and exiting the menu fixes it

### ISSUE THREAD

**Issue by rsn8887** [TheOfficialFloW/Adrenaline#339]
When I just start up a PS1 game, I often get significant, easily noticable slowdown, regardless of filter choice. When I then enter the Adrenaline menu and exit it, it then becomes smooth again.

This is a different issue independent of my previous "screen tearing" issue. This is a much stronger slowdown. Since entering the Adrenaline menu and exiting it again seems to completely fix this type of slowdown, it is not a big deal.

**Comment by derWeihnachtsmann** [comment]
This also happens on my psp.. It's a Sony feature I believe

**Comment by TheOfficialFloW** [comment]
Is this only available in PS1 games?

**Comment by rsn8887** [comment]
No I saw this same problem also while navigating the PSP menu on my VitaTV. The scrolling of menu items became slow. When I entered and exited the Adrenaline menu, it went away.

**Comment by TheOfficialFloW** [comment]
Is it also available if no filter is applied?

**Comment by rsn8887** [comment]
No, only with filter.

Here’s how to reproduce the slowdown in PS1 games.

- start Adrenaline 
- enter menu
- select smooth graphics and sharp bilinear or any other filter
-Exit Menu 
- enter menu
- select exit pspemu (to save settings)
- restart adrenaline 
- load the ps1 game “Lomax”
- observe slowdown in game: jerky/stuttery scrolling
- enter and exit Adrenaline menu
- observe slow down is gone

Concerning slowdown in PSP menu, I think I only observed it on my VitaTV but not on handheld Vita. I am not sure how to reproduce it.

**Comment by rsn8887** [comment]
I tested the slowdown in PSP menu on Vita TV again. I am able to reproduce what i saw before, jerky scrolling in PSP menu. It must have been because I had “bilinear” selected. In fact it only happens whenever “bilinear” filter is selected. Since bilinear is known to cause screen tearing and slowdown, I think the  issue under discussion here is only about PS1 games..

**Comment by TheOfficialFloW** [comment]
Can the issue in PSP menu also be fixed by entering Adrenaline menu?

**Comment by rsn8887** [comment]
No it seems I can only fix it by selecting some other filter different than “bilinear”.

**Comment by TheOfficialFloW** [comment]
can you do a ScePspemuSetDisplayConfig(); at the beginning of AdrenalineDraw thread and see if that solves the issue?

**Comment by rsn8887** [comment]
I just tried, but it doesn't solve the issue.

**Comment by rsn8887** [comment]
I am getting somewhere. If I call "ExitAdrenalineMenu();" once, just whenever pops is started, the slowdown disappears.

Here's the code snippet in AdrenalineDraw() that makes it work, I added a bit of code around the while(1):
```
  int lastPops = 0;

  while (1) {
    SceAdrenaline *adrenaline = (SceAdrenaline *)CONVERT_ADDRESS(ADRENALINE_ADDRESS);
    
    if (!adrenaline->pops_mode) {
      lastPops = 0;
    }
    
    if (adrenaline->pops_mode && lastPops == 0) {
      ExitAdrenalineMenu();
      lastPops = 1;
    }
```

**Comment by TheOfficialFloW** [comment]
Can you test what subroutine of ExitAdrenaline fixes the issue then? Thx!

**Comment by rsn8887** [comment]
It is just a waitvblank that fixes it! It only has to be called once when entering POPS. I am making a PR in 5 minutes.

**Comment by TheOfficialFloW** [comment]
This is weird. The while loop does a vblankwait anyways. Are you really sure about that?

**Comment by rsn8887** [comment]
I made a mistake... hmm
One second.

**Comment by rsn8887** [comment]
Never mind, the PR is correct (!) I cannot claim I understand it, but I just checked and re-checked and verified it about 20 times. Without this extra vblankwait I get slow-down in PS1 every time until I enter/exit menu. With this vblank instruction, no slowdown.

**Comment by rsn8887** [comment]
The extra vblankwait causes one additional single frame delay whenever pops is launched I think, and  somehow that fixes the slowdown issue...

**Comment by rsn8887** [comment]
Hmm the slowdown just happened again. It is MUCH less frequent now, but I just saw it again :(

I suspect I have to pause/unpause pops to make sure it never happens anymore. I will prepare another PR after about 30 minutes more testing..
