### ISSUE TITLE
Adrenaline 3.1 - PS button press in PS1 game freezes No option to exit game (PSTV)

### ISSUE THREAD

**Issue by simbin** [TheOfficialFloW/Adrenaline#34]
Adrenaline 3.0 is okay but in 3.1 something changed. This is on (PSTV)

When you press the PS button in PS1 game, screen freezes (pauses) flickers and you have No option to exit game.

Unless you revert to Adrenaline 3.0, you have no option to to exit game and return to XMB.

**Comment by CelesteBlue-dev** [comment]
Have you tried V4 ?
You can use Freakler's Adrenaline Easy Installer to easily update Adrenaline.

**Comment by simbin** [comment]
I'll test when I get home. No mention in v4 Changelog however.

**Comment by simbin** [comment]
Seems to be fixed in v4 - Only had issue with v3.1 (AdrenalineEasyInstaller v1.09)
