### ISSUE TITLE
WLAN Multiplayer

### ISSUE THREAD

**Issue by maks9597** [TheOfficialFloW/Adrenaline#341]
i observe when tested various games with WLAN mode, that some of them, mostly those of 2005-2006, one of the first on the PSP, work incorrectly. More precisely, there is some kind of problem when connecting, PSVita systems cannot connect with each other. For example: Shinobido, The Sensha (Japan Tank Game), Battlezone

**Comment by nifcapili** [comment]
I have similar issues, to add, earlier psp titles have tendency to disconnect while in WLAN Ad-hoc multiplayer in games like bomberman and metal slug anthology, usually when other players join the game [ps vita as a host] or when ps vita joins a game

**Comment by barneyyenrabx** [comment]
Yes i noticed this ,,, really want to play bomberman with another adhoc player but it gives connection errors ,,, does anybody know hoe to make this work?
