### ISSUE TITLE
Adrenaline has a list limit for PSP games

### ISSUE THREAD

**Issue by BWuuuu** [TheOfficialFloW/Adrenaline#345]
Like the title implies, Adrenaline limits the number of PSP games displayed on the XMB menu by 128, meaning that anything more wont be displayed on the list until I delete previous games. As far as I do recall, I dont remember this kind of limit on a real PSP. I use no plugins on Adrenaline and the recovery menu settings are pretty much set to default besides [Not showing DLCs] and [No gameboot icon] (which I disabled to try if this changed anything but no success).

This is especially weird considering the XMB menu can display more than 150 PS1 games from my official 64GB memory card (the PSP games are on my sd2vita). Would really appreciate a fix, thanks.

**Comment by TheOfficialFloW** [comment]
I think 128 games are enough. And yes, the old custom firmwares had this limitation too.

**Comment by rsn8887** [comment]
Use GC Lite Plugin, see here:
http://wololo.net/talk/viewtopic.php?t=7371

I have over 400 games sorted into many categories like “CAT_PS1 A-L” etc. No problem. Works on Adrenaline and real PSP.

**Comment by BWuuuu** [comment]
Yes, I think that's a good workaround for the moment: make small folders to not hit the max display limit for PSP games right away, and restart Adrenaline if this happens.

**Comment by rsn8887** [comment]
There's no need to restart Adrenaline. The GC Lite Plugin is a PSP plugin it works perfect with Adrenaline. You will see many different folders on your PSP screen, each folder can have 128 games. You just have to enable the plugin in "SEPLUGINS" and create subfolders starting with "CAT_" inside your pspemu/psp/game and pspemu/iso folders. When the plugin runs, a new setting will appear were you can configure how it should appear. I use "multiple MS". This means you will see multiple memory stick icons, one for each category.
