### ISSUE TITLE
Cannot input name for Busou Shinki: Battle Masters Mk. 2

### ISSUE THREAD

**Issue by BWuuuu** [TheOfficialFloW/Adrenaline#346]
When prompted at the beginning of the game to choose a name, the game uses the Vita digital keyboard rather than the PSP digital keyboard (like it should be normally), and any input attempt is automatically erased when pressing the green button Enter. Thus, it's impossible to continue further on past this point.

**Comment by BWuuuu** [comment]
I dont seem to see any option present in the recovery menu (either in configuration and advanced settings) that make you swap the digital keyboards.

**Comment by TheOfficialFloW** [comment]
Use Sony OSK.

**Comment by BWuuuu** [comment]
Oh I see. Thanks a lot.
