### ISSUE TITLE
Garbled text Issue

### ISSUE THREAD

**Issue by XKennyChowX** [TheOfficialFloW/Adrenaline#348]
If I use Chinese to name a rom inside the emulator in Adrenaline (e.g. gpsp) , the name will become garbled text.

**Comment by TheOfficialFloW** [comment]
How is this related to Adrenaline?

**Comment by XKennyChowX** [comment]
Since the display was normal in TN-V in lower version ps vita and normal in ark. Also, it was normal in the PSP. Therefore, I think that because of the Adrenaline font make the word become garbled.
