### ISSUE TITLE
i was told to press x for 661.pbp installation... i pressed X  but it doesnt work

### ISSUE THREAD

**Issue by PablexxBoca** [TheOfficialFloW/Adrenaline#350]
_Originally posted by @akbarsanjaya in https://github.com/TheOfficialFloW/Adrenaline/issues/211#issuecomment-372887777_

**Comment by csvwolf** [comment]
I solved by the following steps from [reddit](https://www.reddit.com/r/vitahacks/comments/71x9mf/adrenaline_installation_failure/):

> I believe 'ux0:app/PSPEMUCFW' is the directory you're after. In older versions of adrenaline it was elsewhere.
> To install adrenaline with a manually downloaded psp update file:
> -Ensure you're using '6.61 Adrenaline-6 fix' (https://github.com/TheOfficialFloW/Adrenaline/releases). Install the VPK.
> -Run adrenaline once and quit when it says it cant find the 661.PBP file (if you dont do this and instead manually create the PSPEMUCFW folder, adrenaline seems to wipe and recreate it when launched the first time).
> -Download http://du01.psp.update.playstation.org/update/psp/image/us/2014_1212_6be8878f475ac5b1a499b95ab2f7d301/EBOOT.PBP
> -Rename it to 661.PBP
> -Transfer to 'ux0:app/PSPEMUCFW' via FTP or USB with vitashell
> -Ensure you have edited ux0:tai/config.txt (edit ur0:tai/config.txt instead if using an sd2vita) to add the line 'ux0:app/PSPEMUCFW/sce_module/adrenaline_kernel.skprx' in the '*KERNEL' section, as per https://github.com/TheOfficialFloW/Adrenaline/blob/master/readme.md
> -Reboot the vita after editing the config.txt
> -Run Adrenaline from the live area
> -Thank TheFlow :)
