### ISSUE TITLE
Adrenaline seems to freeze and then crash when quitting Monster Hunter Freedom Unite

### ISSUE THREAD

**Issue by Itay080** [TheOfficialFloW/Adrenaline#351]
Adrenaline seems to freeze and then crash when quitting Monster Hunter Freedom Unite.
After crashing, Adrenaline keeps crashing whenever you open it and the only way to stop it from crashing is to restart your Vita.
You can reproduce this issue by simply trying to quit Monster Hunter Freedom Unite using the PS button at any stage of the game (I tried to quit before starting a new save file).

**Comment by TheOfficialFloW** [comment]
Hum, try disabling high memory layout in recovery menu (press R while booting Adrenaline).
