### ISSUE TITLE
Native Video Application Freezing on Playback

### ISSUE THREAD

**Issue by n3rt46** [TheOfficialFloW/Adrenaline#354]
Model: PCH-1001
Firmware: Henkaku Enso 3.65
Adrenaline version: 6.7

This issue appears to be related to #306.

All things considered, this is a very niche use-case scenario and isn't necessarily a major feature issue/request considering the Vita has it's own video player. 

I've tried several times to load some video files using the native video player on the XMB, however, doing so causes the entire system to temporarily freeze up before erroring out. Ultimately, this error causes the system to become largely unresponsive to the point where a hard reset needs to be performed (as in, holding the power button to the extent that it restarts into the safe mode menu).

I thought that this might have occurred due to an incompatibility with the native player for playing back certain video/audio codecs, however, this did not seem to be the case; I tried re-encoding the file using several different codecs, however, the native player noted for some that the file was unplayable (it couldn't recognize one of the codecs I tried), but would show others as playable and correctly identified the codec used under the file information. That being said, for the files it showed as playable, the thumbnails still would not load. The files weren't outrageously large either: 480x270, ~13 minutes, ~50MiB.

I don't have a PSP to compare behavior against, that said, I could find no mention of any such error for real PSPs. If I had to guess, I would assume that this problem causes a memory leak.

**Comment by TheOfficialFloW** [comment]
Yeah videos are not supported in Adrenaline.
