### ISSUE TITLE
Remove useless PSP modules to save space?

### ISSUE THREAD

**Issue by pthfdr-42** [TheOfficialFloW/Adrenaline#355]
Since there are already utilities on the Vita itself, I think that maybe you can remove some useless features to slim the PSP firmware down. Since it is not actually PSP hardware, it should be harmless.
[This](http://forums.dashhacks.com/psp-tutorials-guides/148882-free-space-flash0.html) indicates some part of the firmware that can be removed. It is an old post and applies to 3.xx firmware, though.

**Comment by TheOfficialFloW** [comment]
Wow you really want to save a few mb of space...wtf
