### ISSUE TITLE
Feature Request: Use the "O Button Behavior" Setting in "HENkaku Settings" to determine O Button Behavior in Adrenaline menus

### ISSUE THREAD

**Issue by 01y** [TheOfficialFloW/Adrenaline#358]
Having a Japanese Vita with "O Button Behavior" set to "Cancel" under "HENkaku Settings" will still leave "O" as "Accept" within the PSP menus (for instance after pressing the PS button to exit the game). This can be confusing when the contrary function occurs in subsequent menus (such as Adrenaline settings).

**Comment by dude22072** [comment]
Just change the O button setting in the PSP registry.
