### ISSUE TITLE
ERROR OxFFFFFFFF 

### ISSUE THREAD

**Issue by gavinskie25** [TheOfficialFloW/Adrenaline#363]
I already downloaded the adrenaline app but I deleted it because the games that i transfer is not being read, then i try to install again the adrenaline.VPK file and it only shows the ERROR OxFFFFFFFF 

How to Fix This issue , and some of vpk file is getting the same issue like VHBB.vpk 
thanks for your time if you notice this

**Comment by opoisso893** [comment]
Error 0xFFFFFFFF when installing vpk = corrupted vpk
Try to redownload and/or retry transfert to Vita
