### ISSUE TITLE
DS4 controller not working with PSX games at all (Adrenaline/Vita OLED 3G 100x).

### ISSUE THREAD

**Issue by yodafire** [TheOfficialFloW/Adrenaline#366]
Hi,
I have a major problem here, I just got a new DS4 controller, its V2, and had it all set up yesterday.
Now I tried various games to test, I started with this:

PSP Games = They work with the DS4 controller
PS Vita Games = They work with the DS4 controller
Various emulator games = They work with the DS4 controller
PSX Games = Do NOT work with DS4 controller.

The controller operates fine when being used in adrenaline, it can access menu options etc. However when a PSX game is launched, it will only allow the controller to access the settings for adrenaline when holding the ps button down on the DS4 controller, but regrettably it will not allow you to play the game as the controls do not function from the controller to the games.

I have tried all variations of different PSX games, some from NPS others from rom sites, again no dice, refuses to co-operate.

Currently I am on this:

*) PS Vita OLED 3G
*) Adrenaline (Latest release)
*) ds4 plugin (latest release)
*) DS4 controller V2
*) ds4 option ON from adrenaline settings menu.

I have asked on the reddit forums, but no one seems to know how to fix or be able to provide help based on my problem.

https://redd.it/a97ssj

I can also confirm that when I disconnect the controller (deactivate via bluetooth), then run the game using the vitas controls, apparently the same thing happens, I am unsure as to what is causing this, but I am fairly certain this could be with Adrenaline itself. As I am now unable to play any of the PSX games via the vita controls itself, and the DS4 controller.

I can play all other games (PSP/Vita) just fine with the controller and the vitas controls perfect fine, just problems are inlay-ed with the PSX games and adrenaline not allowing me to use the controls on the games when launched.

Any help would be nice :)

Thanks

**Comment by yodafire** [comment]
> You need to use MiniVitaTv

thanks for the reply much appreciated ;).

okay so once i install this plugin alongside my ds4 plugin, the controller will or should then start functioning as normal on the psx game? 

I will give this a go in a few hours, just at work doing late shifts.

please dont close this until i can confirm the above.

thanks.

**Comment by TheOfficialFloW** [comment]
No you will have to deinstall your current ds4 plugin. Minivitatv IS the ds4 driver. It‘s still beta tho, so physical can currently not b used. Also you should use it with the latest Adrenaline.

**Comment by yodafire** [comment]
will this be okay to use with hencore 368> sorry i forgot to mention that, im at home now and ready to give this a whirl once more. if it requires enso only then do let me know before i try this out. ill get rid of the ds4 plugin now before i initially start and for your confirmation :)

**Comment by TheOfficialFloW** [comment]
Yes h-encore is good and no, enso is not required.

**Comment by yodafire** [comment]
okay wait it connect i had to reboot :/

**Comment by yodafire** [comment]
let me try in adrenaline now wont be long :)

**Comment by yodafire** [comment]
yeahhhhh :) hellll yeah flow you are a life saver :) its working, so long as i can use the controller just like this avoiding the 2 warnings in the readme, ill be happy playing ps1 games from now on thanks again for the help.  you can close this help topic and mark as resolved :) A+
