### ISSUE TITLE
Disappearing titles glitch (XMB cosmetic bug)

### ISSUE THREAD

**Issue by Tail870** [TheOfficialFloW/Adrenaline#368]
Found glitch when editing settings in PSP's settings menu. After editing nickname (after leaving PSVita IME) the XMB's labels are mising until entering/exiting to any sub-menus.
Expected after leaving PSVita IME:
![2018-12-26-170449](https://user-images.githubusercontent.com/17884460/50530023-dbfed400-0b0a-11e9-9b86-a4eaadc2154d.jpg)

Reality after leaving PSVita IME:
![2018-12-26-170500](https://user-images.githubusercontent.com/17884460/50530027-e4efa580-0b0a-11e9-820f-35748911ee34.jpg)
Tested languages: Russian, English, Spanish.

**Comment by TheOfficialFloW** [comment]
Yes that‘s a known issue and I couldn‘t find a way to fix it :/
