### ISSUE TITLE
126 PSP game limit?

### ISSUE THREAD

**Issue by kaymynd** [TheOfficialFloW/Adrenaline#373]
Not sure if this is normal but,
Adrenaline only shows 126 psp games maximum and unless restarted will not find any more games. I have 150 psp games and the remaining 24 psp games will not show up. I have used game categories lite to seperate games in different folders but the 126 game limit persists. Once 126 psp games are loaded the rest of the folders will appear empty and say (there are no games. Content can be downloaded or purchased from ps store). Even though there is games. I'm unsure if psx games are affected as well, i only have around 10 so far but I'm planning on adding more and will update once i know for sure if psx games are also affected. If possible please fix this!! I would greatly appreciate it!!

**Comment by TheOfficialFloW** [comment]
Yeah that‘s limit of isos...

**Comment by kaymynd** [comment]
Is it feasible to think that the limit can be surpassed? Or is it just not possible at all?

**Comment by rsn8887** [comment]
PSX games are definitely NOT affected. I just scrolled through >250 PSX games several times and they all display perfectly.

I haven’t tested with psp games (I don’t have so many).

I am using the latest category_lite.prx plugin. I remember I had some problems with older versions of the plugin. Here’s the download of you want to test it: 
https://mega.nz/#!tcRSxaID!5ksGoMGa3JaG5ZW9mdXWLNhWhI9lEJYsYtTCrYDc79k

**Comment by kaymynd** [comment]
Good to know! I'm only at about 80 something PSX games so far, so thanks for testing! And thank you for the link! i just downloaded the plugin,  i will test it once I'm home from work.
