### ISSUE TITLE
Jackass: The Game (EUR/USA) - Original ISO support

### ISSUE THREAD

**Issue by Catarax** [TheOfficialFloW/Adrenaline#375]
The game Jackass is know to have security measure to avoid the use of a ripped version.
There is some patch apparently to skip the measure but the game will lock to the first chapter and multiplayer/challenge modes are disabled.

The original iso file (USA/EUR) runs well on original PSP but not on Adrenaline at all, the game is stuck at the main loading screen.

**Comment by kaymynd** [comment]
Can i ask what the security measure was? I currently have jackass iso working fine on adrenaline. It seems to play well, no errors or bugs, but I've only beaten the first 2 challenges so far.
