### ISSUE TITLE
Nearest Neighbor filter?

### ISSUE THREAD

**Issue by pthfdr-42** [TheOfficialFloW/Adrenaline#376]
Could you consider adding this option? It perserves hard edges and works well on "pixel art" games, especially at irregular zoom levels. Also it is less demanding than the bilinear filter.

**Comment by Valis77** [comment]
I agree that is most important because when i was in Adrenaline settings Mode it had Nearest Neighbor filter in the game background and it looked perfect. I was hoping they can add it but when i exit Adrenaline settings Mode it went smoothed filter on me -_-'

**Comment by InitialXKO** [comment]
Try official shader and turning off bilinear in official menu.

**Comment by pthfdr-42** [comment]
Well, if I choose official ones it has the blurring problem.
I think that a better idea is to use standalone ".cg", ".cgx" and ".filter" files instead of presets, so everyone can use their own.

**Comment by Valis77** [comment]
> Try official shader and turning off bilinear in official menu.

The problem with that is that it lags and the key framerate doesn't keeps a smooth 60fps. It kinda jitters a lot. I think that's what pthfdr-42 is also talking about as well as the filter.

**Comment by Valis77** [comment]
> Well, if I choose official ones it has the blurring problem.
> I think that a better idea is to use standalone ".cg", ".cgp" and ".filter" files instead of presets, so everyone can use their own.

They updated it download their latest adrenaline files and select * Sharp Bilinear withouhg Scanlines* Option and you will get the same results as the original filter. ^_^

**Comment by Valis77** [comment]
> Well, if I choose official ones it has the blurring problem.
> I think that a better idea is to use standalone ".cg", ".cgp" and ".filter" files instead of presets, so everyone can use their own.

They updated! Download their latest adrenaline files and select * Sharp Bilinear withouhg Scanlines* Option and you will get the same results as the original filter. ^_^
