### ISSUE TITLE
Loading saved state doesn't work for Dissidia 012: Duodecim Final Fantasy

### ISSUE THREAD

**Issue by lemourin** [TheOfficialFloW/Adrenaline#38]
Here is what shows up when the saved state is loaded: 
![2017-04-18-232120](https://cloud.githubusercontent.com/assets/11277986/25154000/0548e3e6-248f-11e7-974c-d5b4ce2eddf2.jpg)

Tested using adrenaline v4

**Comment by TheOfficialFloW** [comment]
Resume to livearea and then come back.
