### ISSUE TITLE
Crash on every game when trying to enter text

### ISSUE THREAD

**Issue by MinikPLayer** [TheOfficialFloW/Adrenaline#384]
As the title says the Adrenaline 6.7 crashes every time when there is a text to enter.
Crashes after ~0.5s after the keyboard appears.

Info:
PS VITA Phat 3.60 ( downgraded from 3.68 )
Adrenaline 6.7
Games loaded from uma0 ( official memory card with storagemgr 3.0 ):
- Need for Speed Most Wanted 5.1.0 ( iso )
- Star Wars Battlefront ( PS Store download )

EDIT: Solved itself after VITA reset

**Comment by simplyargyll** [comment]
Hi, i am having the same issue, how did you fix it exactly, what did you mean after vita reset?

**Comment by MinikPLayer** [comment]
Disable all user plugins in config.txt ( find *ALL and add above it *!PSPEMUCFW ).
