### ISSUE TITLE
The performance is lower in games of psx is in adrenaline v4 than in previous versions

### ISSUE THREAD

**Issue by Serhi0** [TheOfficialFloW/Adrenaline#39]
Comparing the performance of the games is less(ex: v3.1). I do not know if it's because of the filters. Maybe you can watch it. Thank you

**Comment by Serhi0** [comment]
This problem does not seem to affect pstv.

**Comment by fsrogi5393** [comment]
I noticed that too in both Tekken 3 and Crash Wraped. Also tried different filter variations and 333/166 cpu clock speed but didn't seem to fix the problem.

**Comment by FlexingTiger** [comment]
Try this:

> - Added screen mode adjustment for PS1 games. If you're using this feature on a PS Vita, select 'Original' screen mode in the
>     offical settings, then apply the custom screen mode.

**Comment by reiyu13** [comment]
Very evident with Tomba.  The beginning of the game is laggy.

**Comment by rsn8887** [comment]
I think the solution would be to bring back the "official" screen mode setting that was removed in latest version. But there is quite a bit of code that was removed related to that setting.

**Comment by slickrasta** [comment]
It seems to be the new ps1 display options as 3.1 is flawless with FF7 but 4.0 has frame rate issues consistently. Even tried setting to original in Adrenaline and full in original settings it doesn't help. I'm stoked 3.1 works great though and has save state! =)

**Comment by Pereb** [comment]
Getting similar framerate drops on PSP games aswell, most noticeably Tales of Eternia can't play videos at a smooth framerate with v4. v3.1 works perfectly.

**Comment by slickrasta** [comment]
Anyone test v4.1 to compare? I assume it's the same as v4 for performance?

**Comment by rsn8887** [comment]
Somebody named Andre made a comment on Wololo: "PS1 speed confirmed still NOT fixed, guys."

So I fear the performance is the same as 4.1 and still not as good as the 3.x versions...

**Comment by TheOfficialFloW** [comment]
https://github.com/TheOfficialFloW/Adrenaline/commit/4059344b3f0a19e1e7324be6943bb4793d9ac09d
