### ISSUE TITLE
Resistance Retribution crashing

### ISSUE THREAD

**Issue by scarz0ftime** [TheOfficialFloW/Adrenaline#398]
Resistance Retribution crashes on the new version of Adrenaline (6.8). It is confirmed working in 6.7, and the issue occurs across multiple ISOs and CSOs of the game in different regions. No other plugins were loaded in taiHEN config.txt and the issue still occurred.

Vita 1000 unit

**Comment by kamilb880** [comment]
Hi, since issue is closed - what is the solution? I've got exactly the same problem.
