### ISSUE TITLE
Kingdom Hearts BBS Final Mix translation not booting

### ISSUE THREAD

**Issue by xperia64** [TheOfficialFloW/Adrenaline#4]
As the title says, the BBS Final Mix translation still does not seem to boot. I have tried multiple versions, and all three ISO drivers, but the game still will not boot.
The one that's been commonly floating around does not work under Ark, but I believe it works under PPSSPP and a real PSP.
A freshly-patched version will boot under Ark and everything else I've tried it on, but not Adrenaline.

**Comment by TheOfficialFloW** [comment]
Send me link to game.

**Comment by xperia64** [comment]
I have sent you two links via Twitter.

**Comment by TheOfficialFloW** [comment]
Haven't seen.

**Comment by xperia64** [comment]
https://pastebin.com/8AttxLvE

**Comment by anthonyn0919** [comment]
I am also having issues with the game. Currently using a CSO of Kingdom Hearts BBS Final Mix with the 1.0.12 Patch applied.

**Comment by Draugluindav** [comment]
I haven't tried but maybe it could help. http://forums.ppsspp.org/showthread.php?tid=22787

**Comment by TheOfficialFloW** [comment]
https://github.com/TheOfficialFloW/Adrenaline/commit/bd83a4da7777cdb8b56c4a75cac906f618258e18
