### ISSUE TITLE
error c2-12828-1 trying to access official menu

### ISSUE THREAD

**Issue by lordnial** [TheOfficialFloW/Adrenaline#400]
after installing adrenaline 6.8 i get error c2-12828-1 when trying to access the official psp menu in adrenaline. then after adrenaline closes i have to hard reboot due to non of my apps will launch.

**Comment by TheOfficialFloW** [comment]
disable your plugins.

**Comment by cristianadonis** [comment]
> deshabilita tus plugins.

Which plugins should I disable?
