### ISSUE TITLE
BUG game psx frezze without wifi

### ISSUE THREAD

**Issue by limonetas** [TheOfficialFloW/Adrenaline#401]
hi, I have the original psvita oled with v3.68 + H-encore 2.0 and the latest version adrenaline.

¿how i discovered?
when turning on the handeld console but it has to be WiFi disconnected at the beginning, initiate h-encore and adrenaline, execute any psx game, for me mine was (the emperor's new groove game).
play 2 min and touch the off button 1 time, until the lights stop blinking, touch the button again to light it plays 2 min and the image freezes. 

the funny thing that if you are connected with WiFi does not freeze the game

I know I'm bad with English but everything was translated by Google

**Comment by rsn8887** [comment]
This is a known problem with ALL homebrew. All filehandles are closed on suspend. When you resume a homebrew that had open file handles, the file operations will cause errors.

**Comment by limonetas** [comment]
> 
> 
> This is a known problem with ALL homebrew. All filehandles are closed on suspend. When you resume a homebrew that had open file handles, the file operations will cause errors.

but doing the same method with activated WiFi does not cause freezing and no errors, ¿does not it sound weird?
