### ISSUE TITLE
Khbbs broken by 6.9

### ISSUE THREAD

**Issue by AdmiralPurple** [TheOfficialFloW/Adrenaline#406]
Black screen on launch for kingdom hearts birth by sleep final mix after updating to 6.9. Worked fine on 6.8.

**Comment by TheOfficialFloW** [comment]
Do you have the new gta plugin enabled?

**Comment by AdmiralPurple** [comment]
Yes I do. Should I try with it disabled? Also super fast reply haha

**Comment by TheOfficialFloW** [comment]
Can you next time read the readme?
