### ISSUE TITLE
undefined reference to `vita2d_create_empty_texture_data' 

### ISSUE THREAD

**Issue by thulk14** [TheOfficialFloW/Adrenaline#407]
Cannot compile adrenaline v6.90, it says:
undefined reference to `vita2d_create_empty_texture_data'
So in order to compile it, we need the updated dependencies of vita2d.

**Comment by thulk14** [comment]
Please make pull a request of your changes in vita2d to "https://github.com/frangarcj/libvita2d/tree/fbo"
So we can be able to to use it.
Thanks.

**Comment by TheOfficialFloW** [comment]
Done https://github.com/frangarcj/vita2dlib/pull/5.
