### ISSUE TITLE
error c2-12828-1 trying to access official menu adrenaline 6.8 and 6.9

### ISSUE THREAD

**Issue by cristianadonis** [TheOfficialFloW/Adrenaline#410]
Adrenaline closes to want to put a name to the psp or access advanced settings for advanced configuration, exiting the error c2-12828-1, it says that I must disable plugins, but I do not know which.

**Comment by H0R1Z0N** [comment]
got the same error trying to access the control for ps1/psp game or system name. Rebuilded database, it failed too. Vita Oled wifi only, vita2sd with 256gb microsd in gameslot.
