### ISSUE TITLE
Battery indicator appears in-game in Tales of Eternia on PSTV.

### ISSUE THREAD

**Issue by MapleStoryPSN** [TheOfficialFloW/Adrenaline#422]
When playing Tales of Eternia on a PSTV, the battery indicator appears at all times (as if it were charging) other than during the FMV's. Any quick fix for this? Spoofing the battery as 100% doesn't fix the issue, as it will still think it's charging.

**Comment by deadair3210** [comment]
Rengoku 2 does the same thing if I remember correctly

**Comment by kristianity77** [comment]
This isn't an issue, it's built in to the actual game. This happens on a legit version of the game on a legit console.

**Comment by deadair3210** [comment]
So it continually shows up? On rengoku it blinks constantly

**Comment by MapleStoryPSN** [comment]
Solved the issue by using TempAR and the settings posted here:

http://www.romhacking.net/forum/index.php?topic=17018.msg270161#msg270161
