### ISSUE TITLE
Dependencies for compiling

### ISSUE THREAD

**Issue by Muzika** [TheOfficialFloW/Adrenaline#43]
Hi TheFloW. Can you list and if possible link all the dependencies needed for compiling Adrenaline? I manage to get some but I really couldn't locate the others. I'm stuck on where to find vitashaders library. I couldn't find it in your repo.

Thank you!

**Comment by pralima87** [comment]
Maybe is this one: https://github.com/frangarcj/vita-shader-collection

**Comment by Muzika** [comment]
@pralima87 

I've already solved that but that's just one. I had 2 left.

/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/6.2.0/../../../../arm-vita-eabi/bin/ld: cannot find -ltaiHEN_stub
/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/6.2.0/../../../../arm-vita-eabi/bin/ld: cannot find -lSceProcessMgr_stub

I already compiled taihen from Yifanlu's source and installed them to vitasdk but it still cannot find the stub. Also not sure where to find SceProcessMgr_stub.

**Comment by usineur** [comment]
I had the same problem. For me, it only was a case problem.

I edited the CMakeLists.txt and replaced the following entries:
- taiHEN_stub -> taihen_stub
- SceProcessMgr_stub -> SceProcessmgr_stub

**Comment by Muzika** [comment]
@usineur 

Thank you!
Found out about taihen_stub and tried SceProcessmgr_stub but now I'm getting this error.

```
CMakeFiles/adrenaline.dir/menu.c.obj: In function `AdrenalineDraw':
menu.c:(.text+0x984): undefined reference to `sharp_bilinear_f'
menu.c:(.text+0x98a): undefined reference to `sharp_bilinear_v'
menu.c:(.text+0x98e): undefined reference to `sharp_bilinear_f'
menu.c:(.text+0x992): undefined reference to `sharp_bilinear_v'
menu.c:(.text+0x99a): undefined reference to `advanced_aa_f'
menu.c:(.text+0x9a0): undefined reference to `advanced_aa_v'
menu.c:(.text+0x9a4): undefined reference to `advanced_aa_f'
menu.c:(.text+0x9a8): undefined reference to `advanced_aa_v'
collect2: error: ld returned 1 exit status
CMakeFiles/adrenaline.dir/build.make:276: recipe for target 'adrenaline' failed
make[2]: *** [adrenaline] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/adrenaline.dir/all' failed
make[1]: *** [CMakeFiles/adrenaline.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

Have you encountered this issue also?

**Comment by frangarcj** [comment]
https://github.com/frangarcj/vita-shader-collection

**Comment by Florin9doi** [comment]
I'll leave the instructions here in case anybody else needs them:

```
git clone https://github.com/frangarcj/vita2dlib.git
cd vita2dlib/libvita2d/
git checkout -b 0001 origin/fbo
make && make install
cd ../sample/
make
cp libvitashaders.a /usr/local/vitasdk/arm-vita-eabi/lib/
```
