### ISSUE TITLE
Categories Lite v1.6

### ISSUE THREAD

**Issue by IcySon55** [TheOfficialFloW/Adrenaline#44]
Hey TheFlow,

Thanks for all this amazing work! I was wondering if you had taken a look at getting Categories Lite fully working yet? From my testing with the CAT prefix enabled, it works for everything in pspemu/PSP/GAME but fails for everything in pspemu/ISO.

I was hoping that you could either fix compatibility with the plugin, or better yet, incorporate the functionality directly into your CFW.

Thanks!

**Comment by slickrasta** [comment]
Homebrew Sorter works al though it doesn't categorize them, just FYI.

**Comment by TheOfficialFloW** [comment]
https://github.com/TheOfficialFloW/Adrenaline/commit/bd83a4da7777cdb8b56c4a75cac906f618258e18
