### ISSUE TITLE
[Feature Request] Option to exit with PS Button

### ISSUE THREAD

**Issue by jkenny23** [TheOfficialFloW/Adrenaline#444]
Is it possible to add a setting to quick exit with the PS button (e.g. normal functionality like in Vita games, to quickly exit the program/PSP emulator)? I'd much rather this than have to hold it down then navigate the menu to exit the emulator.

**Comment by deadair3210** [comment]
Not sure if it hurts anything but I noticed that if you double tap the home button it will go home anyway
