### ISSUE TITLE
Add the ability to run official PSP PSN EBOOT.PBP without license?

### ISSUE THREAD

**Issue by alpakeno** [TheOfficialFloW/Adrenaline#45]
I know it can run PSOne PSN EBOOT.PBP without needing a license or KEYS.BIN.
So how the PSP Game, can it support it too?

**Comment by TheOfficialFloW** [comment]
Use plugin by qwikrazor.

**Comment by alpakeno** [comment]
I know about it, but when it goes to sleep mode and return from it, the game goes corrupted ( no sound as all and hangs while loading ) this happens also in both CFW ( PRO and ME )

**Comment by CelesteBlue-dev** [comment]
@TheOfficialFloW Which plugin by qwikrazor87 ?

**Comment by alpakeno** [comment]
npdrm free, and it has one disadvantage which i said it in my 2nd comment.

**Comment by qwikrazor87** [comment]
@alpakeno that plugin I wrote does not properly handle all decryption processes yet, after finishing the plugin I realized that I messed up with the imports.S in the source code, the import count is not correct, so one function doesn't get resolved, but the plugin still worked with that mess, so I left it at that for now.
I'll need to wait for a laptop before I can fix it.

**Comment by TSDARKNESS** [comment]
@qwikrazor87 thanks for the clarification, I hope you get your laptop ASAP...

**Comment by alpakeno** [comment]
Opps i signed-in using a public computer, so I deleted the post and signed-in using my name...

Anyway thanks @qwikrazor87 for the clarification, I hope you get your laptop ASAP...
