### ISSUE TITLE
Psx cheats do not show in cwcheatpops 

### ISSUE THREAD

**Issue by Ledmen** [TheOfficialFloW/Adrenaline#46]
Dont show any cheats in cwcheat Plugin for Psx 
I try different cheatpops.db still nothing.
Is Adrenaline problem?

**Comment by bosshunter** [comment]
It's not an Adrenaline problem. It shows cheats for PS1 titles.

Maybe you have an incomplete db or missing cheats for your game. Search for Pasky's CWcheat Database Editor and open cheatpops.db to check which game cheats you have.

![recentral 2017-04-19 20-33-59-32](https://cloud.githubusercontent.com/assets/3970315/25198486/9e4fe6ce-253f-11e7-9e34-42376789697a.png)
