### ISSUE TITLE
TempAR not work only in Psx Games (tempar_lite.prx)

### ISSUE THREAD

**Issue by Ledmen** [TheOfficialFloW/Adrenaline#49]
Psx  tempar_lite.prx not working.

Yes i managed run TempAR on psp this version from  
 http://www.theisozone.com/downloads/playstation/psp-plugins/tempar-162-3-cheat-plugin/   
Previously  i tried from
http://wololo.net/talk/viewtopic.php?f=56&t=25415     no luck.

**Comment by TheOfficialFloW** [comment]
Press home then R.

**Comment by falcus123** [comment]
he means the tempar prx for PSX games(Tempar_lite.prx)
cwcheat works in psx mode,but tempar does not seem to open at all in psx games...
maybe when you get the time you can fix this,TheOfficialFlow...
oh and tempar is still working fine with psp games but not psx(using both prx files-tempar.prx/tempar_lite.prx+game and pops.txt with appropriate lines added.)
