### ISSUE TITLE
Large ux0: space remaining issue

### ISSUE THREAD

**Issue by xperia64** [TheOfficialFloW/Adrenaline#5]
I don't know if this can be fixed/patched, or if it's just a hard limitation of pspemu, but when using a large USB storage device (1TB), pspemu reports ~256GB free minus actual used space, and some (most?) games such as Lego Star Wars believe that the memory card is full, probably due to overflow.
Could this be fixed fixed with a plugin that intercepts the storage size syscalls? Something that returns:
1. The max size supported by the PSP if the actual space remaining is greater than the max size
2. The real space available if the actual space remaining is less than the max size

**Comment by FinnYoung** [comment]
i have this problem too with 2TB hard drive. pspemu says that i have ~300-400GB of free space when ~1400GB is available.

**Comment by TheOfficialFloW** [comment]
Fixed in https://github.com/TheOfficialFloW/Adrenaline/commit/f61187a4cdb71f52edff6454ccb6a6f45cf77fc9
