### ISSUE TITLE
PS1 on PSTV is output hell

### ISSUE THREAD

**Issue by Anonanon** [TheOfficialFloW/Adrenaline#51]
I got a PSTV to use it as a PS1 micro console. I own a Vita slim and I thought PS1 games would output more or less the same. I heard that PSTV's 480p mode is somewhat made for playing PS1 games, which would make sense. Turns out this wasn't the case, here are some of my observations, which you may be aware of already:

- PSTV 480p is just 960x544 squished into 720x480
- PS1 mode in 480p is actually just a squished Vita, instead of its own native output (320x240 with 2x clean interger scale, centered on a 720x480 frame)
- PS1 mode in PSTV is permanently on "Normal" display size, out of Original, Normal, Zoom, Full. This destroys the PS1 image quality, "Original" is preferred to preserve 1:1 quality
- "Normal display size" kills the aspect ratio by making things a bit taller for no reason, games look squished. So if you play in PSTV 480p with the aforementioned squishing, it's becomes squished twice.
- PS1 mode in PSTV may have bilinear filtering enabled permanently. "Normal" display size already blurred the image, bilinear filtering would blur it a second time. Adrenaline graphics filtering is already on Official and Smooth Graphics off.

So what I'd like to see is a PS1 display mode that works similarly to Vita where it's a clean 2x integer scaled image, centered in Original screen mode, no smoothing/bilinear filtering.

Case 1: [in-game](https://puu.sh/vriRr.gif)
Case 2: [map](https://puu.sh/vriRB.gif) (notice the circles look extremely warped)

There is one last thing. These screenshots above are internal screenshots that the Vita OS spits out. In reality when it gets sent out to a display, it looks a lot worse. But the point is, I think I found a bug.

In 480p mode, the bottom of the game is actually cut off. However it fixes itself when you bring up the official settings until you close the menu then it goes back to being cut off. Not only is the bottom cut off ingame, but a 1px row is also cut off from the top if you look closely. [Comparison](https://puu.sh/vriRV.gif)

And thanks for all your hard work.

**Comment by Keiyuu** [comment]
I can confirm this. Having the same issues on my PSTV.
What bugs me most is the incorrect aspect ratio because I'm quite sensitive to that, when games simply don't look right.

I really hope for a fix on the next version.

Keep up the great work and thanks for making this possible!
