### ISSUE TITLE
Analog stick problem in psx v4

### ISSUE THREAD

**Issue by xswqaz** [TheOfficialFloW/Adrenaline#53]
Analog stick works at first, But after that did not work

**Comment by bosshunter** [comment]
I never had this problem. And I already tested a lot of ps1 games.

There are games that has no dualshock support, because they were released before it existed.
Though, for these games, you can assign the left analog stick to the D-Pad through the official settings with "Digital Mode" enabled.

**Comment by xswqaz** [comment]
I meaned Analog Stick in vita not DS

**Comment by bosshunter** [comment]
Dualshock is in fact an Analog Controller..
