### ISSUE TITLE
6.61 Adrenaline-4: unable to use the PS Vita button to switch games on an Eboot.psp game

### ISSUE THREAD

**Issue by mickael28** [TheOfficialFloW/Adrenaline#54]
I managed to load the Striker game in the latest version, but this is an Eboot.pbp file with two games in one. For changing between them, they mention:

https://nicoblog.org/psp/29102/

> This is a disc game it contains both Strider 1 and Strider 2. When you boot the game it will start automatically on Strider 1, to switch games you have to press the Home Button (PS logo button) and select Reset Game, then Select Disc 2 and press X (See images below.)

However, when I click on the PS Vita button I just get the message, do you want to exit the game? So there's no way to switch between the two that I can see... 

Is there a workaround for this? or could a new feature be implemented in a future release please?

Thank you!

**Comment by tamamushiiro** [comment]
Try opening official settings and Reset Game from there? It's in the Adrenaline Menu.

**Comment by mickael28** [comment]
I cannot see any official settings, do you know how to bring them up?

ie, the game has just Start button, then 1P, 2P or options, and inside options just settings for sound, screen, etc.. but nothing to reset.

I think the Reset menu appears when pressing the PS logo button, but if we use Adrenaline and press the PS Button instead we just get the message to quit the game. 

Isn't this a problem for this scenario with Adrenaline?

**Comment by TheOfficialFloW** [comment]
If it was a problem with Adrenaline I wouldn't have closed the issue. Search help somewhere else.

**Comment by mickael28** [comment]
I didn't understand the resolution/your point of view though, so not sure how to research further help.

It seems that game has 2 built-in games:
* if we press the PS button in an original PSP, we get the built-in game menu options (which allow you to reset the game, switch disks, etc)
* if we press the PS Vita button in Adrenaline emulating PSP, we do not get the menu above (hence that I thought it was an edge-case where we were not covering this scenario for this type of games in Adrenaline), what we are getting is a total different menu which doesn't allow you to do anything related to the game. It just allows you to close the game. 

If I find out a way to load the second one I'll put it here for future users, but I cannot think of a way to do it if Adrenaline is not currently handling this scenario.

**Comment by TheOfficialFloW** [comment]
Hold PS Button, choose 'Settings' which will open Adrenaline Menu, then select 'Open Official Settings'...

**Comment by mickael28** [comment]
ahhh... awesome!! Thank you man, I didn't know we could do that. Working the way you mentioned... many thanks!!!
