### ISSUE TITLE
Load state not working.

### ISSUE THREAD

**Issue by aleexiisz57** [TheOfficialFloW/Adrenaline#55]
Hey man you do an amazing job with this emulator, I never had a psp when I was little and now thanks to you i can play my psp games it's awesome thanks!. I'm running this bug where after I updated to V4 of adrenaline I lost all my save states,after checking the folder where they should be they are there but the psp can't read them it shows as if they are all empty in the emulator I saved a new state on V4 and it saved on the same folder as the other states but I still can't see the old ones on the emulator. Thank you for your time and I hope you know what's up.

**Comment by TheOfficialFloW** [comment]
Old savestates are not compatible.
