### ISSUE TITLE
Modded DBZ game

### ISSUE THREAD

**Issue by aleexiisz57** [TheOfficialFloW/Adrenaline#58]
I Have ppsspp on my android and i run some modded DBZ games with no problem but when i try them on the latest version of adrenaline v4 they just dont start, the file types ore .iso. is that a bug or they are just not supported? thank you for your time.

**Comment by bosshunter** [comment]
I tested the modded DBZ Shin Budokai 2 and Tenkaichi Tag Team and they work great.

Which ones are not working for you?

**Comment by aleexiisz57** [comment]
They Are Modded DBZ games on spanish, i get them off youtube. Dragon Ball Infinite wold shin budokai 3.iso, Dragon ball super Shin budokai audio latino (v2).iso. Can you point me to where you got the website where you found those games? or can you at least tell me their full names?
