### ISSUE TITLE
oclockvita incompatible

### ISSUE THREAD

**Issue by masterrite** [TheOfficialFloW/Adrenaline#6]
Two problems:

1. when booting into adrenaline, oclockvita menu shows up by default

2. when trying to start vita games, those games stay on the loading screen. Turning oclockvita off in config.txt reverts the vita game behavior to normal; adding the line`!GAMEID for adrenaline base game` in the config.txt fixes problem one, but vita game problem persists.

Thanks!

**Comment by TheOfficialFloW** [comment]
There is ni reason to us this plugin anyway

**Comment by masterrite** [comment]
yes there is. I found it boost performance in games like YS VIII, or would you like to elaborate?

**Comment by CelesteBlue-dev** [comment]
Latest Adrenaline update seams to overclock GPU and now CPU too : 
// Set ARM frequency to highest
 +	scePowerSetArmClockFrequency(444);
So I think there is no need for oclockvita in Adrenaline...

**Comment by masterrite** [comment]
I know, but I'm talking about oclockvita popping up in adrenaline on startup even though I never used it inside.
I'm also talking about the *vita* games not working after updating to v3 and having three plugins installed.

**Comment by CelesteBlue-dev** [comment]
@masterrite Check your ux0:taihen/config.txt file and don't place oclockvita in *all.
