### ISSUE TITLE
Laggy rythm game

### ISSUE THREAD

**Issue by mugichanofu** [TheOfficialFloW/Adrenaline#62]
I'm messaging you to report a small issue with Adrenaline v4 (perhaps also with older versions as well). There is a slight lag for the game "Project Diva Extend" which renders the game unplayable. I'm not sure if it is input lag or sound lag. From what I hear, the same game available on PSN works with no lag. I would greatly appreciate it if you could come up with a solution in the future when you have time. Thanks in advance!

Game title: Hatsune Miku: Project DIVA Extend
Platform: PSP
Region: Japan
Reference: https://en.wikipedia.org/wiki/Hatsune_Miku:_Project_DIVA_Extend

**Comment by dude22072** [comment]
Does Extend not have the option to delay the timing for this very reason? I know the PSVita Miku games do, but I do not recall if the PSP ones did.

**Comment by mugichanofu** [comment]
Unfortunately, such setting does not exist for Extend. Not sure about the other PSP Miku games, but it was one of the later games, so probably doesn't exist for the other ones too.

**Comment by dude22072** [comment]
Would just like to comment that I've recently been playing Project Diva and Project Diva 2nd and have had no trouble clearing songs even on expert. This issue mentions Project Diva Extend, though, so it's possible this is an issue with specifically that game.
