### ISSUE TITLE
PSP USB Link-up mode doesn't seem to work to transfer gamesaves to PS2

### ISSUE THREAD

**Issue by mickael28** [TheOfficialFloW/Adrenaline#63]
Hi,

There are some games which allowed connectivity between the PSP and PS2, for example to transfer gamesaves between the systems. 

One of those games was 'Outrun 2006' and this is how they explained to connect them:
[http://www.gamesdatabase.org/Media/SYSTEM/Sony_PSP/manual/Formated/Out_Run_2006-_Coast_2_Coast_-_Sega.pdf](url)
> Connect your PSP™ system to your PlayStation®2 with a USB cable.
Select the ‘USB Link-up’ on the both systems. Once connected, all
operations are conducted via the PlayStation®2. 

I've got a Vita running Adrenaline and I'm trying to do just that but when I select the 'USB link-up' option on Adrenaline it just says "PS2 not found", and if I select it on the PS2 it says the opposite: "PSP not found"

Is this something that could be looked at from your end at some point please? I could try a different version if needed if you want me to check from my end if some changes allow the connectivity if you cannot check this setup?

Thanks for the help!

**Comment by mickael28** [comment]
Was it a duplicate, or it won't be supported? or should it work? because I've not managed to link them up yet...

**Comment by TheOfficialFloW** [comment]
Can't be supported...

**Comment by mickael28** [comment]
I see, thanks for letting me know!
