### ISSUE TITLE
Support .DAT files

### ISSUE THREAD

**Issue by YokYokYokYok** [TheOfficialFloW/Adrenaline#66]
Hello
Is it possible as for the PSP to add in the menu the possibility of loading the manual into document.dat?

**Comment by TheOfficialFloW** [comment]
No

**Comment by YokYokYokYok** [comment]
Can you explain why?

**Comment by TheOfficialFloW** [comment]
No

**Comment by YokYokYokYok** [comment]
Hummm Okay ^^  your'e reputation precedes you :)
