### ISSUE TITLE
PS1 titles in fullscreen on PSTV

### ISSUE THREAD

**Issue by bosshunter** [TheOfficialFloW/Adrenaline#7]
By default, on the PSTV there is no option to make PS1 titles in fullscreen, as it only shows "Disc Load Speed" under "Other settings".

Sadly, even if you put the memory card in a PSVita and make it fullscreen and then put it back in the PSTV, it changes it back to default 4:3 size.

I know it's not a Adrenaline issue, but maybe the "Screen Mode" option can be enabled on PSTV somehow?

**Comment by alcmoraes** [comment]
Same here.

Psvita have the option to put games on fullscreen.

Pstv run games as a small square on upper left corner of my TV. No option to settle as fullscreen.

**Comment by vipertongn** [comment]
even then though, we don't have the ability to customize screen location, I have mine that cuts off at the bottom of the screen in fullscreen mode

**Comment by TheOfficialFloW** [comment]
Will be added in the next update.
