### ISSUE TITLE
PS1 PSTV Resolution 

### ISSUE THREAD

**Issue by chchris25** [TheOfficialFloW/Adrenaline#72]
PS1 games don't fill the screen when playing on PSTV (There are black bars on top and bottom)

A possible fix is to add custom screen mode to resize the image to fill your TV screen.

**Comment by TheOfficialFloW** [comment]
There is already such a feature lol

**Comment by chchris25** [comment]
How do you access that on PSTV? The custom screen mode is only on the "Official Settings" when playing on the Vita. However this feature is disabled on the PSTV.

**Comment by TheOfficialFloW** [comment]
Open Adrenaline Menu. Also seek help somewhere else.

**Comment by chchris25** [comment]
Thanks and I apologize
