### ISSUE TITLE
New PS1 scaling on both Vita and Vita TV (Adrenaline 4.1 & 5)

### ISSUE THREAD

**Issue by IcySon55** [TheOfficialFloW/Adrenaline#73]
It's nice that the settings now perform what some users were asking for.

What's now missing in 4.1 is the option that I was using, a full screen option.

4.0 - Full - Used to be full screen.
4.1 - Full - Now looks like a widescreen stretch letterboxed (black bars top and bottom).

Can a new option "Stretch" be added in 4.2 that acts like 4.0 Full so that I can get the games full screen again?

Thanks.

**Comment by IcySon55** [comment]
An update.

On Adrenaline 5, while using the original filter, the PSX scaling options don't do anything and instead the screen size is controlled through the official settings.

Official settings sadly don't have a full screen stretch mode but at least have a touch top and bottom aspect ratio maintaining mode (Custom) that looks pretty good when using the original filter in Adrenaline.

I'm not sure what the best way to handle this really is ATM. I'll have to give it some thought while also including the official settings to see all the various combinations that can be achieved.

**Comment by TheOfficialFloW** [comment]
None of the custom graphics options will work with the original rendering lol
