### ISSUE TITLE
Adrenaline 4.2 corrupted iso bug

### ISSUE THREAD

**Issue by aljoriz** [TheOfficialFloW/Adrenaline#77]
used Adrenaline 4.2 via EasyInstall, when going Memory Stick option I would find a corrupted ISo, can't delete the file but when downgrading to 4.1 no Corrupted ISO

**Comment by Duxter7** [comment]
I agree. Updated adrenaline to 4.2 via system update, also have corrupted iso that i cannot delete.

**Comment by TheOfficialFloW** [comment]
https://github.com/TheOfficialFloW/Adrenaline/commit/4059344b3f0a19e1e7324be6943bb4793d9ac09d
