### ISSUE TITLE
Original graphics filtering mode enables bilinear filtering automatically

### ISSUE THREAD

**Issue by Pereb** [TheOfficialFloW/Adrenaline#79]
Using original graphics filtering mode on Adrenaline menu, with bilinear filtering disabled in the official settings menu.

Starting or exiting a PSP game, as well as exiting a PS1 game causes the Vita to use bilinear filtering, despite it still being disabled in official settings. Putting the Vita in sleep mode, opening the Adrenaline settings or LiveArea will disable it again temporarily. Turning off smooth graphics does not help.

**Comment by kristianity77** [comment]
Why is this closed? This is still happening on the latest version.  Is there are reason for this?
