### ISSUE TITLE
Feature Request for PS1 > Fill Y axis and keep picture ratio

### ISSUE THREAD

**Issue by reiyu13** [TheOfficialFloW/Adrenaline#81]
Currently, the scaler can only Fill Y axis, however the X axis remains unchanged using the "normal" scaling preset within the Vita.  The Adrenaline "normal" scaling stretches a bit, but not enough to fill the whole Y axis of the screen.

It would be best to not have any wasted space on the screen, this would indeed be a good feature for non-pixel perfectionists that just want to have a big picture without distorting the ratio.

**Comment by TheOfficialFloW** [comment]
It does already. It's your game that doesn't.
