### ISSUE TITLE
[PSTV] Adrenaline-5's "Original" filtering breaks Adrenaline-4.1's aspect ratio fix

### ISSUE THREAD

**Issue by Anonanon** [TheOfficialFloW/Adrenaline#83]
It seems when I use the new Original filtering, it breaks your aspect ratio fix from Adrenaline-4.1, either that or it ignores the PS1 screen mode setting entirely.

On the bright side, Original filtering eliminates some of the input lag you get from Bilinear/scanline/AA/LCD filtering, so this is definitely on the right track.

Here's a comparison picture to show the problem: https://my.mixtape.moe/rvpptk.gif

**Comment by TheOfficialFloW** [comment]
The original filter is the original rendering where changing the screen ratio is impossible...
