### ISSUE TITLE
Pressing Screenshot combo gives me the PSP Game Exit Screen sometimes.

### ISSUE THREAD

**Issue by ccfman2004** [TheOfficialFloW/Adrenaline#89]
Frequently when I try to take a screenshot I get the PSP Exit Menu as the screenshot instead of the in game image.  Really annoying.

EDIT: Also I don't like how screenshots are stored in randomly named folders in the screenshot folder.  This makes it very hard to find the screenshot I want as I have to look though several folders with each having only one screenshot each.

**Comment by TheOfficialFloW** [comment]
Whether you like it or not, Sony did it so.

**Comment by ccfman2004** [comment]
Sony did what?

**Comment by TheOfficialFloW** [comment]
Randomizing ?

**Comment by ccfman2004** [comment]
There is nothing that can be done about that? What about my first issue?
