### ISSUE TITLE
Assigning custom buttons/touch doesn't work on PS1 titles

### ISSUE THREAD

**Issue by bosshunter** [TheOfficialFloW/Adrenaline#9]
Neither buttons or touchscreen or rear touch pad assigns works on PS1 titles.
Interestingly, it only works on the quit menu, when you press the PS button.

On the PSTV, there isn't even these options (not a Adrenaline issue, I know).
Though, the assign buttons could come in handy, if it can be enabled somehow.

**Comment by TheOfficialFloW** [comment]
Disable Use DS3/DS4 controller first.

**Comment by bosshunter** [comment]
Ah, you're right! Thanks! 

Is the PSTV missing option part possible to add? If not, please close this.

**Comment by bosshunter** [comment]
A great workaround for this, for the PSTV at least, would be the plugin macrofire.

I could get version 3.0.11 to work in 'vsh' and 'game' modes, but sadly, it doesn't show it's menu on pops.

Maybe it can be fixed with the same type of code like you did with cwcheat?

![recentral 2017-04-18 17-43-52-12](https://cloud.githubusercontent.com/assets/3970315/25142421/b82da25c-245e-11e7-9ef3-83b880462646.png)
