### ISSUE TITLE
PRO Online Client not working

### ISSUE THREAD

**Issue by lightfirst** [TheOfficialFloW/Adrenaline#93]
I try install the PRO Online Client on Adrenaline, But only MHFU working
 ![PSV](http://forums.ppsspp.org/attachment.php?aid=15682)
 ![PPSSPP](http://forums.ppsspp.org/attachment.php?aid=15681)

For most psp games, PRO Online Client required 64mb Memory to work (except MHFU).
I try enable Force high memory layout, but still not working.

**Comment by TheOfficialFloW** [comment]
Should now be fixed

**Comment by lightfirst** [comment]
@TheOfficialFloW   
Still now working yet
 Advanced submenu on PSP2000:
![pro](https://forum.coldbird.net/download/file.php?id=21)

If 64mb Memory is already unlock,  Inferno & NP9660 Iso Cache may be cause.
But I didn't know how to disable it on Adrenaline
