### ISSUE TITLE
Usability Suggestion: Original Filter/Renderer should disable unavailable GUI elements

### ISSUE THREAD

**Issue by mart1n8891** [TheOfficialFloW/Adrenaline#99]
And here comes the next one... It's not obvious that original rendering mode does not work with different aspect ratios/scaling. I had to look through quite some posts and closed issues to find out what's going on and therefore be able to change the settings of my ps1 games appropriately. That's a first world problem, of course, but to avoid further annyoing "issues" it'd be easier if you just disable aspect ratio/scaling settings when "Original" is set.

BTW: Thanks for your great work.

**Comment by TheOfficialFloW** [comment]
The message added in v5.1 should be clear enough....

**Comment by mart1n8891** [comment]
Thanks for the quick response. I have to admit that I did not even see that message at first. The message is clear.
